### ISSUE TITLE
objectGUID contains "5c" makes the filter parser fails to parse

### ISSUE THREAD

**Issue by krizex** [cannatag/ldap3#1000]
ldap3 version: 2.9.1
Python: 3.8.10

When I trying to search with filter "(objectguid=db6ffb06-5c7e-432d-a899-7eda79866582)" I got the following error:

```
adagent.domains.connection Operation on LDAP connection[TMP-windows-i3i4uf5.ucc.local] failed Severity=ERROR	Traceback (most recent call last):	  File "/opt/ad-service/adagent/domains/connection.py", line 120, in get_connection	    yield conn	  File "/opt/ad-service/adagent/domains/connection.py", line 134, in get_tmp_connection	    yield c	  File "/opt/ad-service/adagent/ldap/cmd.py", line 160, in _get_connection	    yield conn	  File "/opt/ad-service/adagent/ldap/cmd.py", line 165, in search_objects    await run_in_default_executor(lambda: conn.search(args.search_base, args.s_filter, attributes=['distinguishedName']))	  File "/opt/ad-service/adagent/utils/executor.py", line 19, in run_in_default_executor	    return await run_in_executor(None, func, *args)	  File "/opt/ad-service/adagent/utils/executor.py", line 15, in run_in_executor	    return await loop.run_in_executor(executor, runner)	  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run	    result = self.fn(*self.args, **self.kwargs)	  File "/opt/ad-service/adagent/ldap/cmd.py", line 165, in <lambda>	    await run_in_default_executor(lambda: conn.search(args.search_base, args.s_filter, attributes=['distinguishedName']))	  File "/usr/local/lib/python3.8/dist-packages/ldap3/core/connection.py", line 838, in search	    request = search_operation(search_base,	  File "/usr/local/lib/python3.8/dist-packages/ldap3/operation/search.py", line 371, in search_operation	    request['filter'] = compile_filter(parse_filter(search_filter, schema, auto_escape, auto_encode, validator, check_names).elements[0])  # parse the searchFilter string and compile it starting from the root node	  File "/usr/local/lib/python3.8/dist-packages/ldap3/operation/search.py", line 290, in compile_filter	    matching_filter['assertionValue'] = AssertionValue(prepare_filter_for_sending(filter_node.assertion['value']))  File "/usr/local/lib/python3.8/dist-packages/ldap3/protocol/convert.py", line 215, in prepare_filter_for_sending	    return bytes(ints)	ValueError: bytes must be in range(0, 256) TransactionId=cf2bcf8b-5683-40da-a68a-cbbea6680880
```

It should be a regression of #762

**Comment by krizex** [comment]
The fix (https://github.com/cannatag/ldap3/commit/08ff83621322c4a68455712cd3bae02fc084be36) mentioned in #894 looks incomplete. I think we also have to remove the check https://github.com/cannatag/ldap3/blob/master/ldap3/protocol/convert.py#L201
@cannatag any insights?

**Comment by plettich** [comment]
We have the same issue when using a search filter like `(objectGUID=\\26\\17\\2d\\b9\\ea\\5c\\42\\40\\aa\\c1\\ed\\d9\\49\\c1\\1a\\bc)`.

**Comment by marconfus** [comment]
I can confirm, that the bug was fixed in 2.8 and 2.8.1. 
But it reappeared in 2.9 (and was there in 2.7)

**Comment by derhelge** [comment]
I have tried to replicate the problematic behavior of ldap3 with this simple [script](https://gist.github.com/derhelge/81b2515a9e7d65688c2ca6f564f6b040) as we have a few users with 5c in objectGUID.  The behavior is imho independent of the ldap3 version. Versions 2.8 and 2.8.1 also have the problem.

**Comment by pascalkoenigdaasi** [comment]
I can confirm, that the bug isn't fixed and the problematic behavior still occures on v2.9.1 (and also in v2.8.0, v2.8.1).
I've debugged as described in here: https://github.com/cannatag/ldap3/issues/650#issuecomment-458540224 and see the same behavior in a tcpdump, expected 128 bit (16 byte), delivered in ldap search request 14 byte and also has an incorrect byte **0f** instead of **5c**:

1.) guid in ldap-searchfilter.
2.) guid in tcpdump of the ldap request:
```
\87\f8\d3\76\bd\18\3e\4a\88\fc\10\5c\30\66\ba\86
  87:f8:d3:76: bd:18:3e:4a:88:fc:10:0f:               ba:86
```

This behaviour is reproducable for other objectGUIDs with **5c** byte, that can be simply detected via Script https://gist.github.com/derhelge/81b2515a9e7d65688c2ca6f564f6b040 from @derhelge (many thanks for that).

It looks like that the following part misinterprets the 5c (= 92 decimal) byte as an escaping backslash and modifies the objectGUID value (still same behaviour as described as in the comment https://github.com/cannatag/ldap3/issues/650#issuecomment-458540224 from @fredreichbier:
https://github.com/cannatag/ldap3/blob/v2.9.1/ldap3/protocol/convert.py#L201C1-L201C113

Is there any timeline to fix this issue?

**Comment by gndrmnn** [comment]
There are 3 distinct error cases here:

1) The objectGUID contains a "5C" followed by two byte representations which together form a valid hexadecimal number

2) The objectGUID contains a "5C" followed by two byte representations which together form a negative hexadecimal number

3) The objectGUID contains a "5C" followed by two byte representations which are not valid

1) and 2) both lead to the "5C" being swallowed followed by the two subsequent bytes being interpreted as their ASCII representations and then converted to hex. Most of us experience 1), which leads to an invalid search query and not being able to find the object we are looking for.
Case 2) happens very rarely, only if the "5C" is followed by a "2D" and another hex digit. This then translates to "-<some_digit>" leading to a ``ValueError`` exception, possibly crashing the application.

3) Is irrelevant for this issue here, but leads to #894 


The problem is, that ``prepare_filter_for_sending()`` tries to convert backslashes followed by two digits. This is unnecessary, as the bytes object will not contain escaping backslashes when iterating over it. The ``check_backslash`` was a workaround which only masked the problem and leads to #894. This is because, if invalid hex digits are encountered such as in #894, the ``prepare_filter_for_sending`` will not convert them which is accidentally correct. The addition of ``check_backslash`` breaks #894 as the fix for #1000 is applied without the issue being present.

I created #1171 which should fix the issue. (Hopefully without side-effects)
