### ISSUE TITLE
if ldap port is wrong ldap3.Connection() hangs forever

### ISSUE THREAD

**Issue by fenchu** [cannatag/ldap3#1005]
```
>>> import ldap3
>>> ldap3.__version__
'2.9.1'
```

on windows10

```
python.exe .\bin\ver.py --testenv=test12 --vertical=hso
<after 3minutes I press ctrl+c>      
Traceback (most recent call last):
  File "C:\dist\work\hemit-fullstack-test\bin\ver.py", line 133, in <module>
    if ldap.connect(silent=True):
  File "c:\dist\work\hemit-fullstack-test\tools\FidoLdap.py", line 83, in connect
    self.conn = ldap3.Connection(myserver, self.username, self.pw, auto_bind=True, client_strategy=ldap3.RESTARTABLE)
  File "C:\dist\venvs\hemit-fullstack-test\lib\site-packages\ldap3\core\connection.py", line 363, in __init__
    self._do_auto_bind()
  File "C:\dist\venvs\hemit-fullstack-test\lib\site-packages\ldap3\core\connection.py", line 387, in _do_auto_bind
    self.open(read_server_info=False)
  File "C:\dist\venvs\hemit-fullstack-test\lib\site-packages\ldap3\strategy\restartable.py", line 54, in open
    SyncStrategy.open(self, reset_usage, read_server_info)
  File "C:\dist\venvs\hemit-fullstack-test\lib\site-packages\ldap3\strategy\sync.py", line 57, in open
    BaseStrategy.open(self, reset_usage, read_server_info)
  File "C:\dist\venvs\hemit-fullstack-test\lib\site-packages\ldap3\strategy\base.py", line 134, in open
    self._open_socket(candidate_address, self.connection.server.ssl, unix_socket=self.connection.server.ipc)
  File "C:\dist\venvs\hemit-fullstack-test\lib\site-packages\ldap3\strategy\restartable.py", line 77, in _open_socket
    sleep(self.restartable_sleep_time)
KeyboardInterrupt
```

```
        self.connect_timeout=5
        myserver = ldap3.Server(self.server, port=self.port, get_info=ldap3.ALL, connect_timeout=self.connect_timeout)
        try:
            self.conn = ldap3.Connection(myserver, self.username, self.pw, auto_bind=True, client_strategy=ldap3.RESTARTABLE)
        except (LDAPSocketReceiveError, LDAPSessionTerminatedByServerError, LDAPMaximumRetriesError) as e:
```

It hangs forever if port is wrong, if port is fine all is fine. please let it time out.

**Comment by gumish** [comment]
I have the same problem. Have anybody sorted this issue out?

**Comment by mortenb-buypass** [comment]
You need to have the `raise_exceptions=True`
```
ldap3.set_config_parameter('RESTARTABLE_TRIES', 5)
myserver = ldap3.Server(self.server, port=self.port, get_info=ldap3.ALL, connect_timeout=self.connect_timeout)
try:
    self.conn = ldap3.Connection(myserver, self.username, self.pw, auto_bind=True, client_strategy=ldap3.RESTARTABLE, raise_exceptions=True)
    except (LDAPSocketReceiveError, LDAPSessionTerminatedByServerError, LDAPMaximumRetriesError) as e:
        sys.exit(-1)
    except ldap3.core.exceptions.LDAPSocketOpenError as e:
        sys.exit(-1)
```

**Comment by mortenb-buypass** [comment]
Just like to add after we put this change into our code, you'll get a lot of exceptions, that was ignored before :-)
