### ISSUE TITLE
Bugreport : KeyError when using attributes range in ASYNC mode

### ISSUE THREAD

**Issue by felixcapuano** [cannatag/ldap3#1055]
Hello everyone!

python version 3.9
ldap3 version 2.9.1

## Describe the bug
I would like to set a range for an attributes using range.
**I don't want to use auto_range because I need to manualy set the range.**
My ldap3 connection is in ASYNC strategy.
Python raise the following Exception traceback: 
```bash
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\dev\project\testbench.py", line 29, in <module>
    data, res = connection.get_response(res_id)
  File "C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs\api-anca-mk2bdLis-py3.9\lib\site-packages\ldap3\strategy\base.py", line 440, in get_response
    del entry['raw_attributes'][attribute_type]
  File "C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs\api-anca-mk2bdLis-py3.9\lib\site-packages\ldap3\utils\ciDict.py", line 56, in __delitem__
    del self._store[self._case_insensitive_keymap[ci_key]]
KeyError: 'member'
```

When I try set the attribute to member instead of member;range=0-2 it work otherwise if auto_range is enable the behavior looks random to me.

## Steps to Reproduce
```python
from ldap3 import ASYNC, DEREF_ALWAYS, SIMPLE, SUBTREE, Connection, Server

server = Server(host="<ip>", port="<port>", use_ssl=False )

connection = Connection(
    server=server,
    user="<password>",
    password="<password>",
    authentication=SIMPLE,
    client_strategy=ASYNC,
    auto_bind=True,
    auto_range=False, # I set auto_range to use my own range
)

res_id = connection.search(
    search_base="OU=SILO_T003,OU=AA,DC=ddm,DC=adm,DC=local",
    search_filter="(&(objectClass=group)(cn=Role 1))",
    attributes=["member;range=0-2"], # I set a random range.
    search_scope=SUBTREE,
    dereference_aliases=DEREF_ALWAYS,
    size_limit=100000,
)
data, res = connection.get_response(res_id) # Exception raised here

print(data[0]["attributes"])
```

## What do you believe the expected behavior is
Return member attributes in the range requested

Thank you

**Comment by felixcapuano** [comment]
#1057

**Comment by felixcapuano** [comment]
#1059
