### ISSUE TITLE
tests fail - ImportError: No module named 'pyasn1'

### ISSUE THREAD

**Issue by brianmay** [cannatag/ldap3#116]
Wonder if this is a Python 3.5 specific thing?

```
I: pybuild base:170: cd /«PKGBUILDDIR»/.pybuild/pythonX.Y_3.5/build; python3.5 -m unittest discover -v 
ldap3 (unittest.loader._FailedTest) ... ERROR

======================================================================
ERROR: ldap3 (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: ldap3
Traceback (most recent call last):
  File "/usr/lib/python3.5/unittest/loader.py", line 462, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/lib/python3.5/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/«PKGBUILDDIR»/.pybuild/pythonX.Y_3.5/build/ldap3/__init__.py", line 321, in <module>
    from .core.server import Server
  File "/«PKGBUILDDIR»/.pybuild/pythonX.Y_3.5/build/ldap3/core/server.py", line 36, in <module>
    from .tls import Tls
  File "/«PKGBUILDDIR»/.pybuild/pythonX.Y_3.5/build/ldap3/core/tls.py", line 28, in <module>
    from ..utils.log import log, log_enabled, ERROR, BASIC, NETWORK
  File "/«PKGBUILDDIR»/.pybuild/pythonX.Y_3.5/build/ldap3/utils/log.py", line 30, in <module>
    from ..protocol.rfc4511 import LDAPMessage
  File "/«PKGBUILDDIR»/.pybuild/pythonX.Y_3.5/build/ldap3/protocol/rfc4511.py", line 41, in <module>
    from pyasn1.type.univ import OctetString, Integer, Sequence, Choice, SequenceOf, Boolean, Null, Enumerated, SetOf
ImportError: No module named 'pyasn1'


----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
```

**Comment by brianmay** [comment]
Sorry, filled this report too soon. Looks like I didn't have pyasn1. Oops.

**Comment by cannatag** [comment]
HI Brian,
the pyasn1 decoder were very slow, so I wrote a 10x faster BER decoder. Pyasn1 is used only when sending messages, probably I will remove it sooner or later.

Bye,
Giovanni
