### ISSUE TITLE
extend.standard.modify_password and referrals

### ISSUE THREAD

**Issue by usischev** [cannatag/ldap3#148]
Hello,

I am using ldap3 1.0.4 to connect to two OpenLDAP servers with replication, configured as ServerPool with two entries, both created with `allowed_referral_hosts=[('*', True)]`.

When I call `extend.standard.modify_password` on connection to read-write server it executes successfully. On connection to read-only server, ldap3 receives response with referral from the server.

If this connection has auto_referrals=True, it raises an exception: 
`ldap3.core.exceptions.LDAPReferralError: referral operation not permitted`

If this connection has auto_referrals=False, it raises another exception: `ldap3.core.exceptions.LDAPExtensionError: extended operation error: referral -`

How do I make modify_password work with this configuration?

**Comment by cannatag** [comment]
Hi Pavel, 
auto_referral is not working for extended operations in this release of ldap3. This is because I could not properly test them.  If you want to test them i can try to include this feature in the next release.

Bye, 
Giovanni

**Comment by usischev** [comment]
Giovanni,
Thanks for the response. I can help to test modify_password with referral and would really like to see this feature implemented.

**Comment by cannatag** [comment]
Hi,
can you test the ldap3 version in dev? It should try to follow referrals when performing an extended operation. Can you give me back the extended log of the operation? Just add the following to your testing script:

```
from ldap3.utils.log import set_library_log_detail_level, EXTENDED

logging.basicConfig(filename='pavel-ldap3.log', level=logging.DEBUG)
set_library_log_detail_level(EXTENDED)
```
You should find the pavel-ldap3.log file in the folder where the testing script is run.

Thanks.
Giovanni

**Comment by usischev** [comment]
I made a test script and got the following traceback. Is log file needed to debug this?
```
Traceback (most recent call last):
  File "ldap_referral.py", line 36, in <module>
    r = conn.extend.standard.modify_password(USER, old_password=OLD_PASSWORD, new_password=NEW_PASSWORD)
  File "/Users/pavel/Documents/ldap3-test/ldap3/extend/__init__.py", line 72, in modify_password
    controls).send()
  File "/Users/pavel/Documents/ldap3-test/ldap3/extend/operation.py", line 53, in send
    resp = self.connection.extended(self.request_name, self.request_value, self.controls)
  File "/Users/pavel/Documents/ldap3-test/ldap3/core/connection.py", line 937, in extended
    response = self.post_send_single_response(self.send('extendedReq', request, controls))
  File "/Users/pavel/Documents/ldap3-test/ldap3/strategy/sync.py", line 124, in post_send_single_response
    responses, result = self.get_response(message_id)
  File "/Users/pavel/Documents/ldap3-test/ldap3/strategy/base.py", line 324, in get_response
    ref_response, ref_result = self.do_operation_on_referral(self._outstanding[message_id], responses[-2]['referrals'])
  File "/Users/pavel/Documents/ldap3-test/ldap3/strategy/base.py", line 692, in do_operation_on_referral
    referral_connection.extended(request['requestName'],
KeyError: 'requestName'
```

**Comment by cannatag** [comment]
No, for this error I don't need the log. Will check later and push a patch on GitHub for it.

Thanks,
Giovanni

**Comment by cannatag** [comment]
Please get the code in dev. The keyError should be gone now. Can you check if the referral is working now?

Thanks,
Guivanni

**Comment by usischev** [comment]
I tried current dev branch. In my test script, I have this code:
```
print('Starting...')
with Connection(server, user=USER, password=OLD_PASSWORD, auto_referrals=True, fast_decoder=True) as conn:
	print('LDAP connected: %s' % conn)
```
I waited for over an hour but did not get "LDAP connected" printed. `server` is one Server object without SSL or TLS. Tried to change `auto_referrals` and `fast_decoder`, result is the same. No exception is raised until I press Ctrl+C. Then I get the following traceback:
```
^CTraceback (most recent call last):
  File "ldap_referral.py", line 34, in <module>
    with Connection(servers[0], user=USER, password=OLD_PASSWORD, auto_referrals=True, fast_decoder=True) as conn:
  File "/Users/pavel/Documents/ldap3-test/ldap3/core/connection.py", line 412, in __enter__
    self.bind()
  File "/Users/pavel/Documents/ldap3-test/ldap3/core/connection.py", line 473, in bind
    response = self.post_send_single_response(self.send('bindRequest', request, controls))
  File "/Users/pavel/Documents/ldap3-test/ldap3/strategy/sync.py", line 123, in post_send_single_response
    responses, result = self.get_response(message_id)
  File "/Users/pavel/Documents/ldap3-test/ldap3/strategy/base.py", line 308, in get_response
    responses = self._get_response(message_id)
  File "/Users/pavel/Documents/ldap3-test/ldap3/strategy/sync.py", line 159, in _get_response
    responses = self.receiving()
  File "/Users/pavel/Documents/ldap3-test/ldap3/strategy/sync.py", line 82, in receiving
    data = self.connection.socket.recv(socket_size)
KeyboardInterrupt
```
Version 1.0.4 works fine with the same server.

**Comment by cannatag** [comment]
Hi Pavel,
I know. I introduced a bug in dev, not related to your issue..

 I will check it later today. Sorry for the inconvenience

Giovanni

**Comment by cannatag** [comment]
I've fixed the silly bug in dev. Can you check again?

Thanks,
Giovanni

**Comment by usischev** [comment]
With current dev, if I use connection with fast_decoder=True, I get the following traceback (log file is attached in `pavel-ldap3-log-fast.txt`):
```
Traceback (most recent call last):
  File "ldap_referral.py", line 42, in <module>
    r = conn.extend.standard.modify_password(USER, old_password=OLD_PASSWORD, new_password=NEW_PASSWORD)
  File "/Users/pavel/Documents/ldap3-test/ldap3/extend/__init__.py", line 72, in modify_password
    controls).send()
  File "/Users/pavel/Documents/ldap3-test/ldap3/extend/operation.py", line 53, in send
    resp = self.connection.extended(self.request_name, self.request_value, self.controls)
  File "/Users/pavel/Documents/ldap3-test/ldap3/core/connection.py", line 937, in extended
    response = self.post_send_single_response(self.send('extendedReq', request, controls))
  File "/Users/pavel/Documents/ldap3-test/ldap3/strategy/sync.py", line 124, in post_send_single_response
    responses, result = self.get_response(message_id)
  File "/Users/pavel/Documents/ldap3-test/ldap3/strategy/base.py", line 308, in get_response
    responses = self._get_response(message_id)
  File "/Users/pavel/Documents/ldap3-test/ldap3/strategy/sync.py", line 167, in _get_response
    ldap_resp = decode_message_fast(response)
  File "/Users/pavel/Documents/ldap3-test/ldap3/utils/asn1.py", line 73, in decode_message_fast
    decoded = decode_sequence(message, ber_value_offset, ber_len + ber_value_offset, LDAP_MESSAGE_CONTEXT)
  File "/Users/pavel/Documents/ldap3-test/ldap3/utils/asn1.py", line 93, in decode_sequence
    value = ber_decoder(message, start, start + ber_len, context_decoders)  # call value decode function
  File "/Users/pavel/Documents/ldap3-test/ldap3/utils/asn1.py", line 130, in decode_extended_response
    return decode_sequence(message, start, stop, EXTENDED_RESPONSE_CONTEXT)
  File "/Users/pavel/Documents/ldap3-test/ldap3/utils/asn1.py", line 96, in decode_sequence
    value = context_decoders[ber_type](message, start, start + ber_len)  # call value decode function for context class
KeyError: 3
```
If I use connection with fast_decoder=False and pyasn1 0.1.9 is used, I get the following traceback (log file is attached in `pavel-ldap3-log.txt`):
```
Traceback (most recent call last):
  File "ldap_referral.py", line 41, in <module>
    r = conn.extend.standard.modify_password(USER, old_password=OLD_PASSWORD, new_password=NEW_PASSWORD)
  File "/Users/pavel/Documents/ldap3-test/ldap3/extend/__init__.py", line 72, in modify_password
    controls).send()
  File "/Users/pavel/Documents/ldap3-test/ldap3/extend/operation.py", line 58, in send
    self.decode_response()
  File "/Users/pavel/Documents/ldap3-test/ldap3/extend/operation.py", line 70, in decode_response
    raise LDAPExtensionError('extended operation error: ' + self.result['description'] + ' - ' + self.result['message'])
ldap3.core.exceptions.LDAPExtensionError: extended operation error: protocolError -
```

[pavel-ldap3-log-fast.txt](https://github.com/cannatag/ldap3/files/137990/pavel-ldap3-log-fast.txt)
[pavel-ldap3-log.txt](https://github.com/cannatag/ldap3/files/137991/pavel-ldap3-log.txt)

**Comment by cannatag** [comment]
Hi Pavel,
sorry for bothering you, Could you try the code in dev again with the fast_decoder=False parameter in the Connection object? You should still receive an error, but I have done a minor change that should help me to eventually solve the problem.

Thanks,
Giovanni

**Comment by usischev** [comment]
Giovanni, here is logfile with current code in dev.
[pavel-ldap3-log.txt](https://github.com/cannatag/ldap3/files/144248/pavel-ldap3-log.txt)

**Comment by cannatag** [comment]
Hi Pavel,
can you try again with the latest version in dev? It should (hopefully) run now. The problem was that the request value were encoded again by the asn1 encoder. I also added code to honour in the referral connection the start_tls operation if this was performed in the original connection (this could not apply to your code).

Let me know if it works now. If you still have any problem could you send me back the log? 

Thanks for supporting,
Giovanni

**Comment by usischev** [comment]
Giovanni, here is the exception I got with current dev:
```
Traceback (most recent call last):
  File "ldap_referral.py", line 34, in <module>
    with Connection(servers[0], user=USER, password=OLD_PASSWORD, auto_referrals=True, fast_decoder=False) as conn:
  File "/Users/pavel/Documents/ldap3-test/ldap3/core/connection.py", line 305, in __init__
    log(BASIC, 'instantiated Connection: <%s>', self.repr_with_sensitive_data_stripped())
  File "/Users/pavel/Documents/ldap3-test/ldap3/core/connection.py", line 377, in repr_with_sensitive_data_stripped
    r += '' if self.pool_lifetime is None else ', pool_lifetime={0.pool_lifetime!r}'.format(self),
TypeError: cannot concatenate 'str' and 'tuple' objects
```
Logfile: [pavel-ldap3-log.txt](https://github.com/cannatag/ldap3/files/158453/pavel-ldap3-log.txt)

Also, my servers have TLS enabled, I could do a test with TLS if you want.

**Comment by cannatag** [comment]
Hi Pavel,
this exception is not related to the issue, can you try again with the log disabled?

Thanks for your patience!
Giovanni

**Comment by usischev** [comment]
With logging disabled, it seems to be working. I got the following connection result:
```
{'dn': '', 'referrals': None, 'description': 'success', 'new_password': None, 'responseValue': '', 'result': 0, 'responseName': None, 'message': '', 'type': 'extendedResp'}
```

**Comment by cannatag** [comment]
Good, so it seems that I introduced a new bug... I will check it immediately. Thanks for now.

Giovanni

**Comment by cannatag** [comment]
There were a trailing comma in line 377 of connection.py. Now I fixed it.
If everything is ok for you I'm going to release a new ldap3 version (v1.1.2).

Bye,
Giovanni

**Comment by usischev** [comment]
Everything is ok with following referral, logfile attached just in case.
[pavel-ldap3-log.txt](https://github.com/cannatag/ldap3/files/159330/pavel-ldap3-log.txt)

**Comment by cannatag** [comment]
Thanks for your support Pavel!

Bye,
Giovanni
