### ISSUE TITLE
LDAPSASLBindInProgressError forever raises after network error

### ISSUE THREAD

**Issue by styleex** [cannatag/ldap3#227]
https://github.com/cannatag/ldap3/blob/master/ldap3/core/connection.py#L1072

If a network error during the execution of the functions of authorization, the variable is not set to false. After that, the client always gets exception:

      Traceback (most recent call last):
        File "/usr/lib/python3.5/dist-packages/my_package/application.py", line 201, in rpc_import_security_groups
          ldap_result = await ldap.query_security_groups(domain.domain)
        File "/usr/lib/python3.5/dist-packages/my_package/ldap.py", line 126, in query_security_groups
          conn = await self.get_connection(domain)
        File "/usr/lib/python3.5/dist-packages/my_package/ldap.py", line 122, in get_connection
          conn.bind()
        File "/usr/lib/python3.5/dist-packages/ldap3/core/connection.py", line 535, in bind
          self.refresh_server_info()
        File "/usr/lib/python3.5/dist-packages/ldap3/core/connection.py", line 1125, in refresh_server_info
          self.server.get_info_from_server(self)
        File "/usr/lib/python3.5/dist-packages/ldap3/core/server.py", line 423, in get_info_from_server
          self._get_dsa_info(connection)
        File "/usr/lib/python3.5/dist-packages/ldap3/core/server.py", line 349, in _get_dsa_info
          get_operational_attributes=True)
        File "/usr/lib/python3.5/dist-packages/ldap3/core/connection.py", line 667, in search
          response = self.post_send_search(self.send('searchRequest', request, controls))
        File "/usr/lib/python3.5/dist-packages/ldap3/strategy/base.py", line 283, in send
          raise LDAPSASLBindInProgressError(self.connection.last_error)
      ldap3.core.exceptions.LDAPSASLBindInProgressError: cannot send operation requests while SASL bind is in progress

Need use try..finally block:

    self.sasl_in_progress = True
    try:
        if self.sasl_mechanism == EXTERNAL:
            result = sasl_external(self, controls)
        elif self.sasl_mechanism == DIGEST_MD5:
            result = sasl_digest_md5(self, controls)
        elif self.sasl_mechanism == GSSAPI:
            from ..protocol.sasl.kerberos import sasl_gssapi  # needs the gssapi package
            result = sasl_gssapi(self, controls)
    finally:
        self.sasl_in_progress = False

**Comment by cannatag** [comment]
Hi Styleex. Thanks for your support. I'm about to release version 2 of ldap3. Will check your issues against that version.

**Comment by cannatag** [comment]
included in ldap3 v2.0.3. will be released soon. thanks

**Comment by cannatag** [comment]
Released in 2.0.7
