### ISSUE TITLE
"OPER_member" and "member;range=0-1499" on AD Windows 2016

### ISSUE THREAD

**Issue by sbonnegent** [cannatag/ldap3#228]
Hi,
We use ldap3 since a while, and we are really happy with it :)
Now, we have to test some ldap operations on a fresh new AD with Windows 2016 and we obtain something strange from AD. I don't think it is on ldap3, but if someone have an idea :)

When we do a "ldap3.search()" on a group with 1700 member, we don't obtain attribute "member".
We obtain 2 attributes who doesn't exist on AD: "OPER_member" and "member;range=0-1499".

**Comment by cannatag** [comment]
Hi,
that's a "feature"of AD, when a group exceed the 1000 members limit AD use a quite "obscure" feature of the LDAP protocol that is called "range tag". The problem is that usually until you don't reach that limit you are unaware of it. So your working code breaks without any apparent reason.

ldap3 should handle this for you, try to use the ``auto_range=True`` parameter in the Connection object and the search operation is transparently repeated until the range is exhausted. Your code should work again as before. The "OPER_" prefix is inserted by the ldap3 lilbrary because the attribute name "member" has been changed by the server. It should disappear with the auto_range parameter.

Let me know if this works for you.

Bye,
Giovanni

**Comment by sbonnegent** [comment]
Well, ok, it works with "auto_range=True".

Thanks a lot for this quick help :)

**Comment by balkrish12** [comment]
Can somebody tell me where to set this parameter auto_range=True ?  
Any sample connection object which uses this parameter would be very useful
Thanks in advance for anyone who can help me

**Comment by ankur-karega** [comment]
Did you get the solution for this??

**Comment by cannatag** [comment]
Ho, the parameter is set when defining the connection object with auto_range=True. It should be set to True by default in recent version of ldap3.

Do you still have problems with this feature?

**Comment by jootuom** [comment]
I just ran into this...

`auto_range` does not seem to be working with AD (Server 2016). After running a search, `connection.entries` will only have 1000 results. I had to use the explicit paged query wrapper to fetch all results.

**Comment by sbonnegent** [comment]
With same code, "auto_range" works with 2.7 and below, but failed with 2.8 and 2.8.1. 

```
ldap = ldap3.Connection(
            con["host"],
            user=con["user"],
            password=con["password"],
            auto_bind=True,
            auto_range=True,
        )
ldap.start_tls()
ldap.search(base, filtre, ldap3.SUBTREE, attributes=ldap3.ALL_ATTRIBUTES)
```

```
Traceback (most recent call last):
  File "./manage.py", line 9, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/dsi-django/.venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/opt/dsi-django/.venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/dsi-django/.venv/lib/python3.6/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/dsi-django/.venv/lib/python3.6/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/opt/dsi-django/i2r/si/management/commands/test_sync_group_ad.py", line 49, in handle
    ldap.search(base, filtre, ldap3.SUBTREE, attributes=ldap3.ALL_ATTRIBUTES)
  File "/opt/dsi-django/.venv/lib/python3.6/site-packages/ldap3/core/connection.py", line 839, in search
    response = self.post_send_search(self.send('searchRequest', request, controls))
  File "/opt/dsi-django/.venv/lib/python3.6/site-packages/ldap3/strategy/sync.py", line 139, in post_send_search
    responses, result = self.get_response(message_id)
  File "/opt/dsi-django/.venv/lib/python3.6/site-packages/ldap3/strategy/base.py", line 411, in get_response
    if self.do_search_on_auto_range(self._outstanding[message_id], response):
  File "/opt/dsi-django/.venv/lib/python3.6/site-packages/ldap3/strategy/base.py", line 735, in do_search_on_auto_range
    self.do_next_range_search(request, resp, attr_name)
  File "/opt/dsi-django/.venv/lib/python3.6/site-packages/ldap3/strategy/base.py", line 688, in do_next_range_search
    response['raw_attributes'][attr_type] += current_response['raw_attributes'][attr_name]
TypeError: list indices must be integers or slices, not str
```

**Comment by cannatag** [comment]
Hi, I don't have a Windows Server 2016 for checking this issue. Do you know of any free Internet resource where I can check it?

Thanks,
Giovanni
