### ISSUE TITLE
How to run tests

### ISSUE THREAD

**Issue by mvalkon** [cannatag/ldap3#247]
When trying to run tests for the library on either python 3.5, or python 2.7 I'm getting the following error:

```
(ldap3) emikkva@slartibartfast:~/code/ldap3 (master)
→ ldap3/bin/nosetests -s test
E
======================================================================
ERROR: Failure: Exception (testing location UNKNOWN-EDIR is not valid)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/emikkva/code/ldap3/ldap3/lib/python3.5/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/home/emikkva/code/ldap3/ldap3/lib/python3.5/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/emikkva/code/ldap3/ldap3/lib/python3.5/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/emikkva/code/ldap3/ldap3/lib/python3.5/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/python3.5/imp.py", line 244, in load_module
    return load_package(name, filename)
  File "/usr/lib/python3.5/imp.py", line 216, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/emikkva/code/ldap3/test/__init__.py", line 235, in <module>
    raise Exception('testing location ' + location + ' is not valid')
Exception: testing location UNKNOWN-EDIR is not valid
```

Also I'm seeing most of the tests fail in Travis. Any pointers?

**Comment by cannatag** [comment]
Tests needs a real ldap server to be run. They runs successfully in my lab. I had a cloud lab service that I used on travis but my subscription has expired. Travis should be disabled now. I must find a new ldap online server before reactivation it. 
In the meanwhile if you have a local ldap server to test with you can change the configuration in the__init__.py to point to your server.

Let me know if you need help.

Giovanni

**Comment by mvalkon** [comment]
Thanks for the prompt response @cannatag. We have a live server with which to test against. I'll get back to you if I need help.

**Comment by cannatag** [comment]
Probably the ssl test will fail. You have to change server certificates and issue the user certificate. Also you have to specify the correct server type and location.
