### ISSUE TITLE
Attributes with special chars are not encoded

### ISSUE THREAD

**Issue by cecedille1** [cannatag/ldap3#283]
When I write `()`, it's not encoded unless it contains a `\`. The position of the `\` does not matters.

```
@task
def test_poc():
    import ldap3
    connection = ldap3.Connection('172.20.1.3',
                                  user='cn=admin, dc=pasteur, dc=org',
                                  password='admin',
                                  auto_referrals=False,
                                  raise_exceptions=True)
    connection.bind(read_server_info=False)
    connection.delete('uid=louispas, dc=pasteur, dc=org')
    connection.add('uid=louispas, dc=pasteur, dc=org', ['inetOrgPerson'], {
        'sn': 'Louis Pasteur',
        'cn': 'Louis Pasteur',
        'displayName': 'ab()c,',
        'givenName': 'ab\\()c,',
    })
    connection.search('uid=louispas, dc=pasteur, dc=org',
                      '(objectClass=*)',
                      search_scope=ldap3.BASE,
                      attributes=[
                          ldap3.ALL_ATTRIBUTES,
                          ldap3.ALL_OPERATIONAL_ATTRIBUTES
                      ])
    person = connection.entries[0]

    assert person.givenName == 'ab\\()c,', person.givenName
    assert person.displayName == 'ab()c,', person.displayName
```
```
---> pavement.test_poc
Traceback (most recent call last):
  File "./lib/python3.5/site-packages/paver/tasks.py", line 196, in _run_task
    return do_task()
  File "./venv/lib/python3.5/site-packages/paver/tasks.py", line 193, in do_task
    return func(**kw)
  File "pavement.py", line 148, in test_poc
    assert person.displayName == 'ab()c,', person.displayName
AssertionError: abc\28\29c,
```

I dumped traffic and the 2 properties are not written the same way.
```
00000000  30 81 ad 02 01 03 68 81  a7 04 1e 75 69 64 3d 6c  |0.....h....uid=l|
00000010  6f 75 69 73 70 61 73 2c  64 63 3d 70 61 73 74 65  |ouispas,dc=paste|
00000020  75 72 2c 64 63 3d 6f 72  67 30 81 84 30 15 04 02  |ur,dc=org0..0...|
00000030  73 6e 31 0f 04 0d 4c 6f  75 69 73 20 50 61 73 74  |sn1...Louis Past|
00000040  65 75 72 30 1c 04 0b 64  69 73 70 6c 61 79 4e 61  |eur0...displayNa|
00000050  6d 65 31 0d 04 0b 61 62  63 5c 32 38 5c 32 39 63  |me1...abc\28\29c|
00000060  2c 30 1e 04 0b 6f 62 6a  65 63 74 43 6c 61 73 73  |,0...objectClass|
00000070  31 0f 04 0d 69 6e 65 74  4f 72 67 50 65 72 73 6f  |1...inetOrgPerso|
00000080  6e 30 16 04 09 67 69 76  65 6e 4e 61 6d 65 31 09  |n0...givenName1.|
00000090  04 07 61 62 5c 28 29 63  2c 30 15 04 02 63 6e 31  |..ab\()c,0...cn1|
000000a0  0f 04 0d 4c 6f 75 69 73  20 50 61 73 74 65 75 72  |...Louis Pasteur|
000000b0
```

**Comment by cannatag** [comment]
Can you try the latest code in dev? I'm aware of the problem and should have been fixed. There is a new boolean parameter in the connection object called auto_encode that tries to automatically encode attribute string values from your local encoding. It defaults to True but you can set it to false and use the check_bytes() function in the ldap3.utils.conv package to pass the encoded bytes as the attribute values.

**Comment by cecedille1** [comment]
I cloned the repo and made this (failing) test case. It's not about the non-ascii characters, but about the paranthesis. I think escape_filter_chars should not be called on add and modify operations because it escape for search parameters. RFC 4515 defines escapes only for search filters.

```
import unittest

from ldap3 import MODIFY_REPLACE, MODIFY_ADD, MODIFY_DELETE
from test import random_id, get_connection, add_user, \
    drop_connection, test_base, test_name_attr

testcase_id = random_id()


class Test(unittest.TestCase):
    def setUp(self):
        self.connection = get_connection()
        self.delete_at_teardown = []

    def tearDown(self):
        drop_connection(self.connection, self.delete_at_teardown)
        self.assertFalse(self.connection.bound)

    def get_entry(self, entry_name):
        result = self.connection.search(search_base=test_base, search_filter='(' + test_name_attr + '=' + testcase_id + entry_name + ')', attributes=[test_name_attr, 'givenName'])
        if not self.connection.strategy.sync:
            response, result = self.connection.get_response(result)
            entries = self.connection._get_entries(response)
        else:
            result = self.connection.result
            entries = self.connection.entries
        self.assertEqual(result['description'], 'success')
        self.assertEqual(len(entries), 1)
        return entries[0]

    def test_paranthesis(self):
        self.delete_at_teardown.append(add_user(self.connection, testcase_id, 'modify-1', attributes={'givenName': 'abc(def)'}))
        entry = self.get_entry('modify-1')
        self.assertEqual(entry['givenName'], 'abc(def)')

    def test_paranthesis_backslash(self):
        self.delete_at_teardown.append(add_user(self.connection, testcase_id, 'modify-1', attributes={'givenName': r'abc\(def)'}))
        entry = self.get_entry('modify-1')
        self.assertEqual(entry['givenName'], r'abc\(def)')
```

**Comment by cannatag** [comment]
Are you sure you cloned the DEV repository? This should already be fixed there.

**Comment by cecedille1** [comment]
yes my bad I did it on master. My tests pass on dev. Do you have an expected issue date?

**Comment by cannatag** [comment]
I'm still waiting for users' feedback on other current issues. Hope to release the 2.2 version for next week
