### ISSUE TITLE
Bind fails with OID server

### ISSUE THREAD

**Issue by SanskritFritz** [cannatag/ldap3#312]
My code:
```python
#!/usr/bin/python
from ldap3 import Connection, Server
server = Server( "oid-hu:3060" )
connection = Connection( server, user="cn=orcladmin", password="secretpw" )
connection.bind()
```
The result:
```Traceback (most recent call last):
  File "./connection_test.py", line 11, in <module>
    connection.bind()
  File "/usr/lib/python3.6/site-packages/ldap3-2.2.1-py3.6.egg/ldap3/core/connection.py", line 590, in bind
  File "/usr/lib/python3.6/site-packages/ldap3-2.2.1-py3.6.egg/ldap3/core/connection.py", line 1299, in refresh_server_info
  File "/usr/lib/python3.6/site-packages/ldap3-2.2.1-py3.6.egg/ldap3/core/server.py", line 436, in get_info_from_server
  File "/usr/lib/python3.6/site-packages/ldap3-2.2.1-py3.6.egg/ldap3/core/server.py", line 385, in _get_schema_info
IndexError: list index out of range
```
This worked with pre-2.0 version of ldap3.

Running the script with pudb3 shows the values right before the exception in line 385:
```
>>> connection                                                                                                          
Connection(server=Server(host='oid-hu', port=3060, use_ssl=False, allowed_referral_hosts=[('*', True)],
get_info='SCHEMA'), user='cn=orcladmin', password='secretpw', auto_bind='NONE', version=3, authentication='SIMPLE',
client_strategy='SYNC', auto_referrals=True, check_names=True, read_only=False, lazy=False, raise_exceptions=False,
fast_decoder=True, auto_range=True, return_empty_attributes=True)
```

**Comment by cannatag** [comment]
The server seems to not return the schema, try with get_info=NONE while defining the server object.

**Comment by SanskritFritz** [comment]
This way it works, thank you!
Are there any side effects of the server not returning a schema?

**Comment by cannatag** [comment]
If the schema is known the ldap3 library returns the properly formatted values not the raw values. Also it performs additional checks when querying attributes.

This behavior is active by default in version 2 but it need the schema to know the attribute syntaxes. In version 1 it was disabled by default.

Anyway you don't need it. If your applicator was ok with the version 1 behavior you can ignore this feature.

Bye,
Giovanni

**Comment by SanskritFritz** [comment]
That is good to hear, thanks. Thank you for ldap3, it is a real gem!
