### ISSUE TITLE
client_strategy=LDIF: 'NoneType' object does not support item assignment

### ISSUE THREAD

**Issue by rhoerbe** [cannatag/ldap3#348]
When I do a connection.search a TypeException is thrown that does not lead me to the cause.

````
c.search('dc=at', '(objectclass=*)')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/ldap3/core/connection.py", line 766, in search
    response = self.post_send_search(self.send('searchRequest', request, controls))
  File "/usr/lib/python2.7/site-packages/ldap3/strategy/ldifProducer.py", line 104, in send
    self._outstanding[message_id] = self.connection.request
TypeError: 'NoneType' object does not support item assignment
````
The code reflects the sample from the tutorial, only with different data:

````
s = Server(host, get_info=ALL)
c = Connection(s, admindn, rootpw, auto_bind=True, client_strategy=LDIF)
c.search('dc=at', '(objectclass=*)')
````

**Comment by rhoerbe** [comment]
OK, this was a mix-up of the 2 different things. Thanks for the clarification
