### ISSUE TITLE
PyAsn1Error: Uninitialized ASN.1 value upon `who_am_i` with pyasn1==0.3.2

### ISSUE THREAD

**Issue by thatarchguy** [cannatag/ldap3#395]
Looks like pyasn1 came out with 0.3.2 and it breaks ldap3 again

Related: 
 - https://github.com/cannatag/ldap3/issues/388
 - https://github.com/etingof/pyasn1/issues/52#issuecomment-319696985

```
>>> ad_object.connection.extend.standard.who_am_i()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/opt/case/env/local/lib/python2.7/site-packages/ldap3/extend/__init__.py", line 65, in who_am_i
    controls).send()
  File "/opt/case/env/local/lib/python2.7/site-packages/ldap3/extend/operation.py", line 53, in send
    resp = self.connection.extended(self.request_name, self.request_value, self.controls)
  File "/opt/case/env/local/lib/python2.7/site-packages/ldap3/core/connection.py", line 1169, in extended
    response = self.post_send_single_response(self.send('extendedReq', request, controls))
  File "/opt/case/env/local/lib/python2.7/site-packages/ldap3/strategy/base.py", line 298, in send
    self.connection.request = BaseStrategy.decode_request(message_type, request, controls)
  File "/opt/case/env/local/lib/python2.7/site-packages/ldap3/strategy/base.py", line 623, in decode_request
    result = extended_request_to_dict(component)
  File "/opt/case/env/local/lib/python2.7/site-packages/ldap3/operation/extended.py", line 58, in extended_request_to_dict
    return {'name': str(request['requestName']), 'value': bytes(request['requestValue']) if request['requestValue'] else None}
  File "/opt/case/env/local/lib/python2.7/site-packages/pyasn1/type/base.py", line 269, in __nonzero__
    return self._value and True or False
  File "/opt/case/env/local/lib/python2.7/site-packages/pyasn1/type/base.py", line 186, in plug
    raise error.PyAsn1Error('Uninitialized ASN.1 value ("%s" attribute looked up)' % name)
PyAsn1Error: Uninitialized ASN.1 value ("__nonzero__" attribute looked up)
```

### Workaround (again)
pin `pyasn1==0.2.3`  
  
`pyasn1==0.3.1` was breaking for me as well.

**Comment by thatarchguy** [comment]
Closing issue. 
I was still using ldap==2.2.4. I upgraded to 2.3 and pyasn1 0.3.2 and all is working.
