### ISSUE TITLE
Can't Search By objectSID using MOCK_SYNC on version 2.3

### ISSUE THREAD

**Issue by mprahl** [cannatag/ldap3#396]
Hello,
I have unit tests that tests a function's ability to search Active Directory via objectSID. The JSON file describing the server is located at:
https://github.com/StackFocus/PostMaster/blob/master/tests/ad/ad_ldap_directory.json

When using ldap 2.2.4, I get the following:
```python
import ldap3
mock_server = ldap3.Server('ldaps://server.domain.local:636', get_info=ldap3.OFFLINE_AD_2012_R2)
mock_ldap_connection = ldap3.Connection(mock_server, client_strategy=ldap3.MOCK_SYNC, authentication=ldap3.SIMPLE)
mock_ldap_connection.strategy.entries_from_json('tests/ad/ad_ldap_directory.json')
mock_ldap_connection.open()
mock_ldap_connection.search('DC=postmaster,DC=local', '(&(objectClass=group)(objectSid=S-1-5-21-1270288957-3800934213-3019856503-1607))', ldap3.SUBTREE)
print(mock_ldap_connection.response)
/opt/postmaster/env/local/lib/python2.7/site-packages/ldap3/strategy/mockBase.py:778: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if to_unicode(value1, 'utf-8').lower() == to_unicode(value2, 'utf-8').lower():  # case insensitive comparison
[{'dn': u'CN=PostMaster Admins,OU=Groups,DC=postmaster,DC=local', 'attributes': {}, 'raw_attributes': {}, 'raw_dn': 'CN=PostMaster Admins,OU=Groups,DC=postmaster,DC=local', 'type': 'searchResEntry'}]
```

When using ldap 2.3, I get the following:
```python
import ldap3
mock_server = ldap3.Server('ldaps://server.domain.local:636', get_info=ldap3.OFFLINE_AD_2012_R2)
mock_ldap_connection = ldap3.Connection(mock_server, client_strategy=ldap3.MOCK_SYNC, authentication=ldap3.SIMPLE)
mock_ldap_connection.strategy.entries_from_json('tests/ad/ad_ldap_directory.json')
mock_ldap_connection.open()
mock_ldap_connection.search('DC=postmaster,DC=local', '(&(objectClass=group)(objectSid=S-1-5-21-1270288957-3800934213-3019856503-1607))', ldap3.SUBTREE)
print(mock_ldap_connection.response)
Traceback (most recent call last):
  File "<input>", line 6, in <module>
  File "/opt/postmaster/env/local/lib/python2.7/site-packages/ldap3/core/connection.py", line 765, in search
    response = self.post_send_search(self.send('searchRequest', request, controls))
  File "/opt/postmaster/env/local/lib/python2.7/site-packages/ldap3/strategy/mockSync.py", line 56, in post_send_search
    responses, result = self.mock_search(request, controls)
  File "/opt/postmaster/env/local/lib/python2.7/site-packages/ldap3/strategy/mockBase.py", line 640, in mock_search
    return self._execute_search(request)
  File "/opt/postmaster/env/local/lib/python2.7/site-packages/ldap3/strategy/mockBase.py", line 670, in _execute_search
    matched = self.evaluate_filter_node(filter_root, candidates)
  File "/opt/postmaster/env/local/lib/python2.7/site-packages/ldap3/strategy/mockBase.py", line 742, in evaluate_filter_node
    self.evaluate_filter_node(element, candidates)
  File "/opt/postmaster/env/local/lib/python2.7/site-packages/ldap3/strategy/mockBase.py", line 742, in evaluate_filter_node
    self.evaluate_filter_node(element, candidates)
  File "/opt/postmaster/env/local/lib/python2.7/site-packages/ldap3/strategy/mockBase.py", line 840, in evaluate_filter_node
    if attr_name in self.connection.server.dit[candidate] and self.equal(candidate, attr_name, attr_value):
  File "/opt/postmaster/env/local/lib/python2.7/site-packages/ldap3/strategy/mockBase.py", line 860, in equal
    if self._check_equality(value, attribute_value):
  File "/opt/postmaster/env/local/lib/python2.7/site-packages/ldap3/strategy/mockBase.py", line 879, in _check_equality
    if to_unicode(value1, SERVER_ENCODING).lower() == to_unicode(value2, SERVER_ENCODING).lower():  # case insensitive comparison
  File "/opt/postmaster/env/local/lib/python2.7/site-packages/ldap3/utils/conv.py", line 64, in to_unicode
    raise UnicodeError("Unable to convert client data to unicode: %r" % obj)
UnicodeError: Unable to convert client data to unicode: '\x01\x05\x00\x00\x00\x00\x00\x05\x15\x00\x00\x00=\x12\xb7KE\xa7\x8d\xe2wZ\xff\xb3H\x06\x00\x00'
```

I noticed that starting in ldap3 2.2.2 there was a warning when doing this operation, but what must I do to rectify this?

Thanks for the help.

**Comment by cannatag** [comment]
Please check code in dev. It should work now.

**Comment by mprahl** [comment]
@cannatag yes that worked, thank you. Do you know when you'll make a release?

**Comment by cannatag** [comment]
Hope to release is by the end of the month. 

Bye,
Giovanni
