### ISSUE TITLE
ldap3 does not work with pyasn1==0.2.3 and higher with kerberos auth

### ISSUE THREAD

**Issue by Ivan-Viktorov** [cannatag/ldap3#414]
Hi,

same issue as https://github.com/cannatag/ldap3/issues/304, but with sasl_mechanism=ldap3.KERBEROS.

With this code:
from ldap3 import Server, Connection, ALL, KERBEROS, SASL

srv = Server(host='ldaps://mdc1.szgmu.local:636', get_info=ALL)
c = Connection(srv, authentication=SASL, sasl_mechanism=KERBEROS)
c.bind()

I have exception:
Exception on /upload [GET]
Traceback (most recent call last):
File "/usr/lib/python3.4/site-packages/pyasn1/type/univ.py", line 976, in __str__
return self._value.decode(self.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x82 in position 1: invalid start byte
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/lib/python3.4/site-packages/flask/app.py", line 1982, in wsgi_app
response = self.full_dispatch_request()
File "/usr/lib/python3.4/site-packages/flask/app.py", line 1614, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/lib/python3.4/site-packages/flask/app.py", line 1517, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
raise value
File "/usr/lib/python3.4/site-packages/flask/app.py", line 1612, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/lib/python3.4/site-packages/flask/app.py", line 1598, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "./app/krb5auth.py", line 91, in decorated
response = function(srvCtx.initiator_name, clientCredsToken, *args, **kwargs)
File "./app/views.py", line 19, in upload
c.bind()
File "/usr/lib/python3.4/site-packages/ldap3/core/connection.py", line 538, in bind
response = self.do_sasl_bind(controls)
File "/usr/lib/python3.4/site-packages/ldap3/core/connection.py", line 1233, in do_sasl_bind
result = sasl_gssapi(self, controls)
File "/usr/lib/python3.4/site-packages/ldap3/protocol/sasl/kerberos.py", line 69, in sasl_gssapi
result = send_sasl_negotiation(connection, controls, out_token)
File "/usr/lib/python3.4/site-packages/ldap3/protocol/sasl/sasl.py", line 160, in send_sasl_negotiation
response = connection.post_send_single_response(connection.send('bindRequest', request, controls))
File "/usr/lib/python3.4/site-packages/ldap3/strategy/base.py", line 300, in send
self.connection.request = BaseStrategy.decode_request(message_type, request, controls)
File "/usr/lib/python3.4/site-packages/ldap3/strategy/base.py", line 615, in decode_request
result = bind_request_to_dict(component)
File "/usr/lib/python3.4/site-packages/ldap3/operation/bind.py", line 96, in bind_request_to_dict
'authentication': authentication_choice_to_dict(request['authentication'])}
File "/usr/lib/python3.4/site-packages/ldap3/protocol/convert.py", line 62, in authentication_choice_to_dict
return {'simple': str(authentication_choice['simple']) if authentication_choice.getName() == 'simple' else None, 'sasl': sasl_to_dict(authentication_choice['sasl']) if authentication_choice.getName() == 'sasl' else None}
File "/usr/lib/python3.4/site-packages/ldap3/protocol/convert.py", line 58, in sasl_to_dict
return {'mechanism': str(sasl['mechanism']), 'credentials': str(sasl['credentials'] if sasl['credentials'] is not None and sasl['credentials'].hasValue() else None)}
File "/usr/lib/python3.4/site-packages/pyasn1/type/univ.py", line 980, in __str__
'Can\'t decode string \'%s\' with \'%s\' codec at \'%s\'' % (self._value, self.encoding, self.__class__.__name__)
pyasn1.error.PyAsn1Error: Can't decode string 'b'``\x82\x16]\x06\token hex value\xf0\x8b'' with 'utf-8' codec at 'Credentials'

Same code works with pyasn1==2.2.2, but doesn't work with higher versions.

Centos 7, Python 3.4.5, ldap3 2.3, pyasn1 0.3.6.

**Comment by cannatag** [comment]
Hi. can you check code in dev? I've tried to fix it but I have no access to a Kerberos infrastructure for authentication. If it is still not working can you please send me the value of the "sasl" variable in the sasl_to_dict(sasl) function at line 58 of the ldap3/protocol/convert.py file?

Thanks,
Giovanni

**Comment by tmu-sprd** [comment]
Hi all,

code in dev does work for me now. Had the same issue as Ivan.

Gentoo, Python 3.4.6, ldap3 dev (1c8aa7c), pyasn1 0.3.7

Thank you,
Tino

**Comment by Ivan-Viktorov** [comment]
Hi. Code from dev works as expected. No issues found.

Thank you.
