### ISSUE TITLE
Can't transform read result with extensibleObject into write entry

### ISSUE THREAD

**Issue by daenney** [cannatag/ldap3#455]
So... this involves `extensibleObject` which I'm aware of is an awful idea. But I have to deal with some legacy so here we are :|.

I've defined a user as such:

```python
user = ObjectDef(['inetOrgPerson', 'posixAccount', 'shadowAcount', etc etc])
user += 'sshPublicKey'
```

`sshPublicKey' normally comes from 'ldapPublicKey' from the `openssh-lpk_openldap.schema`. However, since this thing had `extensibleObject` on all user attributes people helpfully forgot to actually add `ldapPublicKey` to the `objectClasses`.

I then issued a search and got results back but needed to modify the results for some of the entries. So I loop over `.entries`, and call `entry_writable()`. At that point I'm greeted with:

```python
Traceback (most recent call last):
  File "/home/daenney/Applications/virtualenvs/mirage/bin/mirage", line 11, in <module>
    load_entry_point('mirage', 'console_scripts', 'mirage')()
  File "/home/daenney/Applications/virtualenvs/mirage/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/daenney/Applications/virtualenvs/mirage/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/daenney/Applications/virtualenvs/mirage/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/daenney/Applications/virtualenvs/mirage/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/daenney/Applications/virtualenvs/mirage/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/daenney/Development/mirage/mirage/cli.py", line 101, in sync
    writable_entry = user_entry.entry_writable()
  File "/home/daenney/Applications/virtualenvs/mirage/lib/python3.6/site-packages/ldap3/abstract/entry.py", line 416, in entry_writable
    writable_entry = writable_cursor._create_entry(self._state.response)
  File "/home/daenney/Applications/virtualenvs/mirage/lib/python3.6/site-packages/ldap3/abstract/cursor.py", line 301, in _create_entry
    entry._state.attributes = self._get_attributes(response, self.definition._attributes, entry)
  File "/home/daenney/Applications/virtualenvs/mirage/lib/python3.6/site-packages/ldap3/abstract/cursor.py", line 244, in _get_attributes
    raise LDAPCursorError(error_message)
ldap3.core.exceptions.LDAPCursorError: attribute 'sshPublicKey' not in object class 'apple-user, extensibleObject, inetOrgPerson, ldapProfile, posixAccount, shadowAccount, sambaSamAccount' for entry <redacted>
```

Now, I thought I could solve this by changing the `ObjectDef` to include `ldapPublicKey` too but then my `search()` fails b/c the filter is constructed based on all of the classes in the `ObjectDef`.

Since this thing includes `extensibleObject` I would expect to be able to call `.entry_writable()` and not hit this snag.

To be honest I'm not sure one would want to fix this, b/c `extensibleObject` but it took me by surprise. In the meam time I'll run a modify by hand to add that object class to everyone first and then carry on.

**Comment by cannatag** [comment]
Hi, I've not implemented the ``extensibleObject`` behaviour in ldap3. I don't see a valid use for it. Anyway if you think it is helpful in some way I will implement it.

**Comment by daenney** [comment]
So, in general I loathe `extensibleObject` and I don't think support for it is really worth it. However, I do think my initial bug report still stands. If you can create a query with an additional AttrDef and then call `.entry_writable' on it you'll be greeted by this error.
