### ISSUE TITLE
"client_strategy = LDIF" results in TypeError

### ISSUE THREAD

**Issue by lhoekenga** [cannatag/ldap3#472]
I am trying to generate an LDIF from an LDAP change event.

The code samples from [the LDAP3 LDIF documentation](http://ldap3.readthedocs.io/ldif.html) result in errors.

```
from ldap3 import MODIFY_ADD, MODIFY_DELETE, MODIFY_REPLACE, Connection, LDIF
connection = Connection(server = None, client_strategy = LDIF)

connection.modify('cn=Paula Jensen,ou=Product Development,dc=airius,dc=com',
    {'postaladdress': (MODIFY_ADD, ['123 Anystreet $ Sunnyvale, CA $ 94086']),
     'description': (MODIFY_DELETE, []),
     'telephonenumber': (MODIFY_REPLACE, ['+1 408 555 1234', '+1 408 555 5678']),
     'facsimiletelephonenumber': (MODIFY_DELETE, ['+1 408 555 9876'])
    })
```

generates the following error..
```
Traceback (most recent call last):
  File "ldiftest.py", line 8, in <module>
    'facsimiletelephonenumber': (MODIFY_DELETE, ['+1 408 555 9876'])
  File "/usr/local/python-3.6.2/lib/python3.6/site-packages/ldap3/core/connection.py", line 1044, in modify
    response = self.post_send_single_response(self.send('modifyRequest', request, controls))
  File "/usr/local/python-3.6.2/lib/python3.6/site-packages/ldap3/strategy/ldifProducer.py", line 104, in send
    self._outstanding[message_id] = self.connection.request
TypeError: 'NoneType' object does not support item assignment

```

**Comment by cannatag** [comment]
Hi, the example is missing the ``connection.open()`` line. Sorry, put it in the blank line.

Bye,
Gioavnni
