### ISSUE TITLE
help invalid filter

### ISSUE THREAD

**Issue by ymcymc** [cannatag/ldap3#476]
hi

i used the filter "(objectClass=group)" to query LDAP group, but got an error,
when i change it to "(objectClass=posixGroup)",  the query code can be worked fine.  i dont know why? 
and the filter "(objectClass=group)" is worked on .Net LDAP code, 

_2018-01-18 16:29:52,421 [7100] LDAP(82) ERROR : query fail
Traceback (most recent call last):
  File "E:\backup\Extneranl Server\ldap.py", line 76, in query
    attributes=ldap3.ALL_ATTRIBUTES)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\ldap3\core\connection.py", line 762, in search
    self.server.schema if self.server else None)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\ldap3\operation\search.py", line 370, in search_operation
    request['filter'] = compile_filter(parse_filter(search_filter, schema, auto_escape, auto_encode).elements[0])  # parse the searchFilter string and compile it starting from the root node
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\ldap3\operation\search.py", line 206, in parse_filter
    current_node.append(evaluate_match(search_filter[start_pos:end_pos], schema, auto_escape, auto_encode))
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\ldap3\operation\search.py", line 166, in evaluate_match
    assertion = {'attr': left_part, 'value': validate_assertion_value(schema, left_part, right_part, auto_escape, auto_encode)}
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\ldap3\protocol\convert.py", line 139, in validate_assertion_value
    value = validate_attribute_value(schema, name, value, auto_encode)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\ldap3\protocol\convert.py", line 153, in validate_attribute_value
    raise LDAPObjectClassError('invalid class in objectClass attribute: ' + str(value))
ldap3.core.exceptions.LDAPObjectClassError: invalid class in objectClass attribute: group_

**Comment by cannatag** [comment]
Hi,
probably your server doesn't return the "group" definition in the schema, but only the "posixGroup". ldap3 by defaults checks that the object classes used in the search filter are present in the server schema. You can change this behaviour with ``check_names=False`` in the Connection() definition.

Let me know if this works.

Bye,
Giovanni

**Comment by ymcymc** [comment]
thank you 
i added "check_names=False ",  but it does not worked.
same error

**Comment by ymcymc** [comment]
my connection code:
self.connection_object = Connection(
            self.server,
            user=self.connection_info.username,
            password=self.connection_info.password,
            version=3,
            check_names=False
        )

search code:
self.connection_object.search(
                    search_base=condition.searchbase,
                    search_filter=condition.searchfilter,
                    search_scope=ldap3.SUBTREE,
                    attributes=ldap3.ALL_ATTRIBUTES)

**Comment by ymcymc** [comment]
ldap group Screenshot
![image](https://user-images.githubusercontent.com/35580261/35123652-2abf5b4a-fc71-11e7-9c56-08d7748442e0.png)

**Comment by cannatag** [comment]
This means that your  server doesn't have a "group" object class. Probably the .Net application translates it to some other name internally.  To be sure you should perform a packet capture of the search operation and check what is actually sent over the wire.  This can be dine with a tool like Wireshark,

**Comment by ymcymc** [comment]
oh sorry,
my code will deploy in the customer environment.
i can not run any tool like Wireshark,

Is there any way to skip this problem and continue to get the data?
Or what other interface can get "objectclass" information before ldap query

**Comment by cannatag** [comment]
Are you sure that you get the same error with check_names=True? It should not run the checking at all. Can you send me the errortrace?

**Comment by ymcymc** [comment]
yes, i am sure
error log screenshot (2 time with check_names=False and check_names=False)
![image](https://user-images.githubusercontent.com/35580261/35124687-04ac0832-fc75-11e7-9b9b-c2577ff5437e.png)

error trace log:
2018-01-18 17:24:59,364 [5548] LDAP(68) INFO : searchBase:dc=maxcrc,dc=com searchFilter:(objectClass=group)
2018-01-18 17:24:59,365 [5548] LDAP(22) INFO : Address:192.168.48.12 Port:389 Username:uid=dfeng,ou=People,dc=maxcrc,dc=com IsSSL:False
2018-01-18 17:24:59,477 [5548] LDAP(56) INFO : Connect Sueccessfully!
2018-01-18 17:24:59,478 [5548] LDAP(83) ERROR : query fail
Traceback (most recent call last):
  File "E:\backup\Extneranl Server\ldap.py", line 77, in query
    attributes=ldap3.ALL_ATTRIBUTES)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\ldap3\core\connection.py", line 762, in search
    self.server.schema if self.server else None)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\ldap3\operation\search.py", line 370, in search_operation
    request['filter'] = compile_filter(parse_filter(search_filter, schema, auto_escape, auto_encode).elements[0])  # parse the searchFilter string and compile it starting from the root node
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\ldap3\operation\search.py", line 206, in parse_filter
    current_node.append(evaluate_match(search_filter[start_pos:end_pos], schema, auto_escape, auto_encode))
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\ldap3\operation\search.py", line 166, in evaluate_match
    assertion = {'attr': left_part, 'value': validate_assertion_value(schema, left_part, right_part, auto_escape, auto_encode)}
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\ldap3\protocol\convert.py", line 139, in validate_assertion_value
    value = validate_attribute_value(schema, name, value, auto_encode)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\ldap3\protocol\convert.py", line 153, in validate_attribute_value
    raise LDAPObjectClassError('invalid class in objectClass attribute: ' + str(value))
ldap3.core.exceptions.LDAPObjectClassError: invalid class in objectClass attribute: group
2018-01-18 17:24:59,483 [5548] LDAP(62) INFO : unbind and close connection
2018-01-18 17:24:59,484 [5548] LDAP(89) DEBUG : None

**Comment by cannatag** [comment]
Please try with get_info=NONE when defining the Server object.  You must import NONE from the ldap3 name space. With this parameter the schema is not read at all from the server and no checking is done.

**Comment by ymcymc** [comment]
Oh !
it is works , now
thank you very much ! 
:)

**Comment by ymcymc** [comment]
i will closed the case.
