### ISSUE TITLE
Getting "cannot convert 'NoValue' object to bytes" on bind

### ISSUE THREAD

**Issue by usethedata** [cannatag/ldap3#505]
On a bind() call to LDAP, I'm getting  cannot convert 'NoValue' object to bytes.  Not sure what I'm doing wrong, but I'd expect an exception, not an error message.

```
>>> ldconn.bind()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/ldap3/core/connection.py", line 427, in bind
    response = self.post_send_single_response(self.send('bindRequest', request, controls))
  File "/usr/lib/python3.6/site-packages/ldap3/strategy/sync.py", line 122, in post_send_single_response
    responses, result = self.get_response(message_id)
  File "/usr/lib/python3.6/site-packages/ldap3/strategy/base.py", line 298, in get_response
    responses = self._get_response(message_id)
  File "/usr/lib/python3.6/site-packages/ldap3/strategy/sync.py", line 168, in _get_response
    dict_response = self.decode_response(ldap_resp)
  File "/usr/lib/python3.6/site-packages/ldap3/strategy/base.py", line 403, in decode_response
    result = bind_response_to_dict(component)
  File "/usr/lib/python3.6/site-packages/ldap3/operation/bind.py", line 119, in bind_response_to_dict
    'saslCreds': bytes(response['serverSaslCreds']) if response['serverSaslCreds'] is not None else None}
  File "/usr/lib/python3.6/site-packages/pyasn1/type/univ.py", line 890, in __bytes__
    return bytes(self._value)
TypeError: cannot convert 'NoValue' object to bytes
```

Details:
    OS: Red Hat Enterprise Linux Workstation release 7.4 (Maipo) 
    Python: 3.6.3 
    Modules installed:
    configparser (3.5.0)
    pip (9.0.1) 
    pyasn1 (0.4.2)
    python3-ldap (0.9.8.4)
    setuptools (38.5.1)
    wheel (0.30.0)

code (with server name, etc changed):

```
import ldap3
lds = ldap3.Server("ldap.mydomain.org", use_ssl=True)
ldconn = ldap3.Connection(lds, user="cn=org1,ou=sites,ou=accounts,dc=mydomain,dc=org", password="monkey", read_only=True)
ldconn.bind()
```

**Comment by cannatag** [comment]
Hi, you're using a very, very old version of ldap3 (0.9.8.4), that is not compatible with pyasn1 0.4.2. You should upgrade to ldap3 version 2.4.1, that is much more reliable and faster. You probably will find some incompatibility between version 0.9.8.4 and 2.4.1 of ldap3, but most of them are just import issues.

Let me know if you need help with the newer version.

Bye,
Giovanni

**Comment by usethedata** [comment]
Thanks.  Sorry to have not checked that.  I installed using `python -m pip` and assumed that would be an up-to-date version.  Will update and then re-open if it's still an issue, with some additional troubleshooting.
