### ISSUE TITLE
ldap3.core.exceptions.LDAPSessionTerminatedByServerError: session terminated by server

### ISSUE THREAD

**Issue by nehagodwal** [cannatag/ldap3#513]
am trying to run the code which is trying to build a connection:

server = Server(host='localhost', port=33389, use_ssl=False, get_info=ALL)
conn = Connection(server, user='uid=admin,ou=people,dc=example,dc=org', password=user-pass, raise_exceptions=False, authentication=SIMPLE)
print(server.info)
print(conn)

None
ldap://localhost:33389 - cleartext - user: uid=admin,ou=people,dc=hadoop,dc=apache,dc=org - not lazy - unbound - closed - - tls not started - not listening - SyncStrategy - internal decoder

Traceback (most recent call last):
File "knox_connect.py", line 116, in 
main()
File "knox_connect.py", line 112, in main
print(get_knox_users())
File "knox_connect.py", line 63, in get_knox_users
conn.open()
File "/usr/local/lib/python3.5/dist-packages/ldap3/strategy/sync.py", line 59, in open
self.connection.refresh_server_info()
File "/usr/local/lib/python3.5/dist-packages/ldap3/core/connection.py", line 1325, in refresh_server_info
self.server.get_info_from_server(self)
File "/usr/local/lib/python3.5/dist-packages/ldap3/core/server.py", line 448, in get_info_from_server
self._get_dsa_info(connection)
File "/usr/local/lib/python3.5/dist-packages/ldap3/core/server.py", line 364, in _get_dsa_info
get_operational_attributes=True)
File "/usr/local/lib/python3.5/dist-packages/ldap3/core/connection.py", line 775, in search
response = self.post_send_search(self.send('searchRequest', request, controls))
File "/usr/local/lib/python3.5/dist-packages/ldap3/strategy/sync.py", line 142, in post_send_search
responses, result = self.get_response(message_id)
File "/usr/local/lib/python3.5/dist-packages/ldap3/strategy/base.py", line 345, in get_response
raise LDAPSessionTerminatedByServerError(self.connection.last_error)
ldap3.core.exceptions.LDAPSessionTerminatedByServerError: session terminated by server

**Comment by cannatag** [comment]
Your server deliberately close the connection. Are you sure you are authorized to connect to it? Also try with get_info=NONE when creating the server object, maybe your server is configured to not allow reading the schema.

**Comment by cannatag** [comment]
Hi, any news on this issue? I've just released the 2.5 version of ldap3. Can you give a try?

**Comment by djlambert** [comment]
I think I'm also seeing this issue on the dev branch. It worked a couple days ago, not sure what changed. Trying to debug now, will post my findings.

**Comment by djlambert** [comment]
Nevermind, must be an issue with the DC (Windows Server 2003). Works fine with a different server (Windows Server 2008R2)

**Comment by djlambert** [comment]
You're welcome. I wasn't the one who originally opened the issue though.
