### ISSUE TITLE
Use threading, queue with ldap3 to query Active Directory

### ISSUE THREAD

**Issue by JostLuebbe** [cannatag/ldap3#544]
Hello, I have been attempting to get a program working that can query Active Directory as quickly as possible. I believe I have understood the general idea of how to use ldap3 to query the AD as when I do it in a single thread it works fine. Now I would like to speed up the process using threading and queues but have run into issues using the REUSABLE connection. Below you'll find the code I am trying to get working.

```
import ldap3 as ldap
from queue import Queue
import threading

def call(q, c):
    while True:
        dns_name = q.get()
        if dns_name is None:
            break

        if c is None:
            print('Connection Failed')
            break

        search_base = 'company.domain.string.local'
    
        search_base_split = ','.join(['DC=' + x for x in search_base.split('.')])

            params = {
                'search_base': search_base_split,
                'search_filter': '(' + 'CN=' + dns_name + ' )',
                'search_scope': ldap.SUBTREE,
                # 'time_limit': '60'
            }

            try:
                c.bind()
                search_id = c.search(**params)
                if search_id:
                    response = c.get_response(search_id, timeout=60)
                    if len(response[0]) > 0:
                        if len(response[0]) > 1:
                            print(response[0][0]['dn'])
                c.unbind()
            except Exception as e:
                print(e)

        q.task_done()

def ldap_practice_main():
    with open('resources/dns_names.txt', 'r') as f:
        dns_names = f.readlines()

    q = Queue(maxsize=0)

    s = ldap.Server(
        'company.local',
        use_ssl=True,
        # get_info=ldap.ALL
    )

    num_threads = 10

    user = my_username
    password = my_password

    with ldap.Connection(
        s,
        user=user,
        password=password,
        # auto_bind=ldap.AUTO_BIND_NONE,
        authentication=ldap.SIMPLE,
        client_strategy=ldap.REUSABLE,
        collect_usage=True,
        read_only=True,
        lazy=False,
        raise_exceptions=True,
        pool_size=num_threads,
        pool_lifetime=120,
        pool_name='test_pool'
        # pool_keepalive=60,
        # receive_timeout=True,
    ) as c:

        for i in range(num_threads):
            thread = threading.Thread(target=call, args=[q, c])
            thread.setDaemon(True)
            thread.start()

    for dns_name in dns_names:
        q.put(dns_name.strip())

    q.join()


if __name__ == '__main__':
    try:
        ldap_practice_main()
    except Exception as e:
        print(str(e))
```

This is a somewhat simplified version of the code I am using but the idea is the same. I run into various errors when I run it. Some threads work fine and return the information I expect, and then others randomly throw a bunch of different errors, such as LDAPMaximumRetriesError, LDAPSocketReceiveError, LDAPOperationsErrorResult, LDAPSocketOpenError.

I'm not sure if I've understood correctly how to use a REUSABLE connection pool and open multiple connections simultaneously on the same server to search for different dns names. Any guidance you could provide would be very helpful. I can also supply the longer error messages I get.

**Comment by cannatag** [comment]
The REUSABLE connection handles thread internally and it’s intented to be used in specific scenarios on some long standing server applications and it’s not well tested. It’s not faster than creating RESTARTABLE connections from the same Server object. What errors are you receiving in your code?

**Comment by JostLuebbe** [comment]
Hello,

Thanks for responding so quickly. Here are the errors I get when running that code. I believe the first error produces the second.

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\python\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\python\lib\site-packages\ldap3\strategy\reusable.py", line 258, in run
    response = self.worker.connection.post_send_search(self.worker.connection.send(message_type, request, controls))
  File "C:\python\lib\site-packages\ldap3\strategy\restartable.py", line 246, in post_send_search
    raise exc
  File "C:\python\lib\site-packages\ldap3\strategy\restartable.py", line 232, in post_send_search
    ret_value = SyncStrategy.post_send_search(self, self.connection.send(self._current_message_type, self._current_request, self._current_controls))
  File "C:\python\lib\site-packages\ldap3\strategy\sync.py", line 142, in post_send_search
    responses, result = self.get_response(message_id)
  File "C:\python\lib\site-packages\ldap3\strategy\base.py", line 358, in get_response
    ref_response, ref_result = self.do_operation_on_referral(self._outstanding[message_id], responses[-2]['referrals'])
  File "C:\python\lib\site-packages\ldap3\strategy\base.py", line 755, in do_operation_on_referral
    referral_connection.open()
  File "C:\python\lib\site-packages\ldap3\strategy\sync.py", line 56, in open
    BaseStrategy.open(self, reset_usage, read_server_info)
  File "C:\python\lib\site-packages\ldap3\strategy\base.py", line 145, in open
    raise LDAPSocketOpenError('unable to open socket', exception_history)
ldap3.core.exceptions.LDAPSocketOpenError: ('unable to open socket', [(datetime.datetime(2018, 6, 18, 10, 18, 42, 23872), <class 'ldap3.core.exceptions.LDAPSocketOpenError'>, LDAPSocketOpenError('socket connection error while opening: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',), ('10.213.16.11', 636)), (datetime.datetime(2018, 6, 18, 10, 19, 3, 21872), <class 'ldap3.core.exceptions.LDAPSocketOpenError'>, LDAPSocketOpenError('socket connection error while opening: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',), ('10.213.16.10', 636))])
```

```
Traceback (most recent call last):
  File "C:/PyCharm Projects/Misc Programs/ldap_practice.py", line 48, in call
    response = c.get_response(search_id, timeout=60)
  File "C:\python\lib\site-packages\ldap3\strategy\reusable.py", line 475, in get_response
    raise LDAPResponseTimeoutError('no response from worker threads in Reusable connection')
ldap3.core.exceptions.LDAPResponseTimeoutError: no response from worker threads in Reusable connection
```

I can also try with a RESTARTABLE connection if you think that would work better. Would I just create a connection per thread?

**Comment by cannatag** [comment]
Yes, try with the RESTARTABLE, so we can understand if the error is caused by the multithreading structure of the REUSABLE connection. The SSL: WRONG_VERSION_NUMBER let me think of an error in ssl configuration on the server.

**Comment by JostLuebbe** [comment]
Multiple threads, each creating a separate RESTARTABLE connection works much better and its faster than a single thread. No errors are thrown. I believe this will be my solution. Thanks for your guidance.
