### ISSUE TITLE
Getting "ldap3.core.exceptions.LDAPSocketOpenError: invalid server address" with 'with Connection'

### ISSUE THREAD

**Issue by thakurmhn** [cannatag/ldap3#546]
Hi
I am using following variables and trying use with Conneciont()

Env: Python27
 
ldapserver = 'ldps1.example.com'
admindn = 'admin'
secret = 'secr3t'
basedn = 'ou=pci_policy,ou=People,dc=example,dc=com'

>>> with Connection(server, "\'uid=%s,'%s'\', '%s', auto_bind=True, auto_referrals=False" % (admindn, basedn, secret)) as conn:
...     print(conn)
...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/ldap3/core/connection.py", line 470, in __enter__
    self.open()
  File "/usr/lib/python2.7/site-packages/ldap3/strategy/sync.py", line 56, in open
    BaseStrategy.open(self, reset_usage, read_server_info)
  File "/usr/lib/python2.7/site-packages/ldap3/strategy/base.py", line 149, in open
    raise LDAPSocketOpenError('invalid server address')
ldap3.core.exceptions.LDAPSocketOpenError: invalid server address

However when used like below it works fine 

>>> conn=Connection(server, "\'uid=%s,'%s'\', '%s', auto_bind=True" % (admindn, basedn, secret))
>>> print(conn)
ldap://'ldps1.example.com' use_ssl=True, get_info=ALL:389 - cleartext - user: 'uid=admin,'ou=pci_policy,ou=People,dc=example,dc=com'', 'secr3t', auto_bind=True - not lazy - unbound - closed - <no socket> - tls not started - not listening - SyncStrategy - internal decoder

**Comment by cannatag** [comment]
Hi, it seems that your misusing the % operator. Try to properly specify each parameter of the connection. For example: 

with Connection(server, “uid=%s, %s” % (admindn,  basedn), secret), auto_bind=True) as conn:

You must be sure that your server is accepting connections on the 389 port or 636 port. In the latter case you should set use_ssl to True.
