### ISSUE TITLE
ad_modify_password() failes with 'invalid attribute type unicodePwd'

### ISSUE THREAD

**Issue by eradman** [cannatag/ldap3#547]
I am attempting to use ldap3 to modify the password for users in AD:

```
import ldap3

server = ldap3.Server("ldap.my.org")

base_dn="dc=my,dc=org"
user_dn="uid=eradman,ou=people,dc=my,dc=org"

with ldap3.Connection(server, user_dn, 'XXX') as conn:
    conn.start_tls()
    conn.search(base_dn, '(&(objectclass=person)(uid=eradman))', attributes=['cn', 'objectclass'])
    for entry in conn.entries:
        print entry

    ldap3.extend.microsoft.modifyPassword.ad_modify_password(conn, user_dn, "XYZ", "ZXY")
```

When I run this I hit the following exception

```
DN: uid=eradman,ou=people,dc=dc=my,dc=org - STATUS: Read - READ TIME: 2018-06-28T14:50:24.170380
    cn: Eric Radman
    objectClass: top
                 person
                 posixAccount
                 shadowAccount

Traceback (most recent call last):
  File "chpass.py", line 16, in <module>
    ldap3.extend.microsoft.modifyPassword.ad_modify_password(conn, user_dn, "XYZ", "ZXY")
  File "/usr/lib/python2.7/site-packages/ldap3/extend/microsoft/modifyPassword.py", line 50, in ad_modify_password
    controls)
  File "/usr/lib/python2.7/site-packages/ldap3/core/connection.py", line 1039, in modify
    raise LDAPAttributeError('invalid attribute type ' + attribute_name_to_check)
ldap3.core.exceptions.LDAPAttributeError: invalid attribute type unicodePwd

```

Is my approach incorrect, or am I hitting a bug?

**Comment by eradman** [comment]
Turns out this was my fault: I was connecting to an OpenLDAP directory, not a Windows AD

**Comment by cannatag** [comment]
😀
