### ISSUE TITLE
How could I implement AD nested group membership searches with MOCK_SYNC?

### ISSUE THREAD

**Issue by mprahl** [cannatag/ldap3#577]
Active Directory supports getting the group membership of a group by also recursively searching the membership of groups that are a member of the initial group with:
```ldap
(&(objectClass=user)(memberOf:1.2.840.113556.1.4.1941:=CN=ADReset Admins,OU=Groups,DC=adreset,DC=local))
```

I'd like my unit tests to support this kind of searching using `MOCK_SYNC` but I get the following traceback:
```
Traceback (most recent call last):
  File "/home/mprahl/git/ADReset2/adreset/ad.py", line 190, in search
    self.base_dn, search_filter, search_scope=search_scope, attributes=attributes)
  File "/home/mprahl/git/ldap3/ldap3/core/connection.py", line 782, in search
    response = self.post_send_search(self.send('searchRequest', request, controls))
  File "/home/mprahl/git/ldap3/ldap3/strategy/mockSync.py", line 56, in post_send_search
    responses, result = self.mock_search(request, controls)
  File "/home/mprahl/git/ldap3/ldap3/strategy/mockBase.py", line 647, in mock_search
    return self._execute_search(request)
  File "/home/mprahl/git/ldap3/ldap3/strategy/mockBase.py", line 659, in _execute_search
    filter_root = parse_filter(request['filter'], self.connection.server.schema, auto_escape=True, auto_encode=False, validator=self.connection.server.custom_validator, check_names=self.connection.check_names)
  File "/home/mprahl/git/ldap3/ldap3/operation/search.py", line 206, in parse_filter
    current_node.append(evaluate_match(search_filter[start_pos:end_pos], schema, auto_escape, auto_encode, validator, check_names))
  File "/home/mprahl/git/ldap3/ldap3/operation/search.py", line 166, in evaluate_match
    assertion = {'attr': left_part, 'value': validate_assertion_value(schema, left_part, right_part, auto_escape, auto_encode, validator, check_names)}
  File "/home/mprahl/git/ldap3/ldap3/protocol/convert.py", line 144, in validate_assertion_value
    value = validate_attribute_value(schema, name, value, auto_encode, validator=validator, check_names=check_names)
  File "/home/mprahl/git/ldap3/ldap3/protocol/convert.py", line 160, in validate_attribute_value
    raise LDAPAttributeError('invalid attribute ' + name)
ldap3.core.exceptions.LDAPAttributeError: invalid attribute ExtensibleMatch:
 matchingRule
```

Could you point me to where I'd need to add this functionality in the code?

**Comment by cannatag** [comment]
the extensibleMatch filter is not supported in mock strategies. This need more investigation...

**Comment by vguhesan** [comment]
Can you guide me on implementing this feature? Or how I would go about it?

Thanks

**Comment by cannatag** [comment]
How is this implemented in AD? The mock strategy should follow the same behavior. I don’t use AD so if you describe how it works I could try to include it in the mock_strategy.

Bye,
Giovanni

**Comment by vguhesan** [comment]
Hi Giovanni:

Thank you for the quick response. I hope you and your family are all safe during this tried times. 

To be honest, I do not know where to begin with how it is implemented in the Microsoft AD. But let me explain what we are trying to do.

In our code, we have a filter-criteria defined as follows:
`filterCriteria = '''(&(ObjectClass=user)
(ObjectCategory=Person)
(!(userAccountControl:1.2.840.113556.1.4.803:=2))
)'''` 

Here are some links to the "extensibleMatch" that we are using:
- [1.2.840.113556.1.4.803](https://ldapwiki.com/wiki/1.2.840.113556.1.4.803)
- [LDAP_MATCHING_RULE_BIT_AND](https://ldapwiki.com/wiki/LDAP_MATCHING_RULE_BIT_AND)
- [Microsoft AD Extensions](https://ldapwiki.com/wiki/Microsoft%20Active%20Directory%20Extensible%20Match%20Rules)

It does a Bit wise AND on a BIT STRING (bitmask) to determine if a particular flag is a enabled. 

**Example**

Say that this userAccountControl has two possible values 514 or 512:

For 514 as the value:

0101 0001 0100
0000 0000 0010  AND
___________________________________

0000 0000 0000 : bit in position 2 from right = 0 
Return FALSE

For 512 as the value:

0101 0001 0010
0000 0000 0010 AND
___________________________________
0000 0000 0010 : bit in position 2 from right = 1
Return TRUE


In our case, we are doing a (!(extensibleMatch)) which will flip the result boolean.

I hope this gives you some detail around this. Please let me know if there is anything additional you would like me to elaborate further. 

Once again, I appreciate your valuable time on this. 

Much appreciated and stay safe and let me know if there is any additional detail you need from me.

Thanks

Best Regards,
Venkatt Guhesan
