### ISSUE TITLE
failed: ImportError: cannot import name NoValue

### ISSUE THREAD

**Issue by Edlopushansky** [cannatag/ldap3#592]
Hello Giovanni, 

Getting this error :
python_lib.BitglassRobot' failed: ImportError: cannot import name NoValue
Traceback (most recent call last):
  File "C:\Automation\qa\robot2\python_lib\__init__.py", line 1, in <module>
    from keywords import *
  File "C:\Automation\qa\robot2\python_lib\keywords\__init__.py", line 5, in <module>
    from AD import *
  File "C:\Automation\qa\robot2\python_lib\keywords\AD\__init__.py", line 6, in <module>
    from _bg_ad_general import _BgActiveDirectoryGeneral     # future AD class
  File "C:\Automation\qa\robot2\python_lib\keywords\AD\_bg_ad_general.py", line 62, in <module>
    from ldap3 import Server, Connection, ALL, MODIFY_REPLACE, ALL_ATTRIBUTES
  File "C:\Python27\lib\site-packages\ldap3\__init__.py", line 138, in <module>
    from .core.connection import Connection
  File "C:\Python27\lib\site-packages\ldap3\core\connection.py", line 37, in <module>
    from ..extend import ExtendedOperationsRoot
  File "C:\Python27\lib\site-packages\ldap3\extend\__init__.py", line 45, in <module>
    from .standard.whoAmI import WhoAmI
  File "C:\Python27\lib\site-packages\ldap3\extend\standard\whoAmI.py", line 27, in <module>
    from pyasn1.type.univ import NoValue
PYTHONPATH:
  C:\Automation\qa\robot2\python_lib\keywords\applications\dropbox\..\..\..\keywords\common
  C:\Python27\lib\site-packages\pip-8.1.2-py2.7.egg
  C:\Windows\system32\python27.zip
  C:\Python27\DLLs
  C:\Python27\lib
  C:\Python27\lib\plat-win
  C:\Python27\lib\lib-tk
  C:\Python27
  C:\Python27\lib\site-packages
  C:\Python27\lib\site-packages\win32
  C:\Python27\lib\site-packages\win32\lib
  C:\Python27\lib\site-packages\Pythonwin
  C:\Automation\qa\robot2

**Comment by Edlopushansky** [comment]
pyasn1 had to be upgraded
