### ISSUE TITLE
Can't start TLS before bind?

### ISSUE THREAD

**Issue by horkko** [cannatag/ldap3#604]
Hi,

I'm just new to ldap3. I'd like to connect to my remote LDAP server using TLS. From what I've read from the documentation, it is possible (with Connection object) to start the TLS before binding (https://ldap3.readthedocs.io/connection.html):
```
auto_bind: automatically opens and binds the connection. Can be AUTO_BIND_NONE, AUTO_BIND_NO_TLS, AUTO_BIND_TLS_AFTER_BIND, AUTO_BIND_TLS_BEFORE_BIND.
....
start_tls: establishes a secure connection, can be executed before or after the bind operation.
```

However, if I do this in my script, I get this error:
Using `auto_bind=AUTO_BIND_TLS_BEFORE_BIND`:
```
Traceback (most recent call last):
  File "ldap_connect.py", line 51, in <module>
    read_only=True)
  File "/Users/tuco/src/workspace/omictools/lib/python3.6/site-packages/ldap3/core/connection.py", line 321, in __init__
    self.do_auto_bind()
  File "/Users/tuco/src/workspace/omictools/lib/python3.6/site-packages/ldap3/core/connection.py", line 349, in do_auto_bind
    raise LDAPBindError(self.last_error)
ldap3.core.exceptions.LDAPBindError: automatic bind not successful
```

Using `conn.start_tls` just before calling `conn.bind()`
```
Can't connect to ldap://54.36.252.50:10389: unable to send message, socket is not open
```

But calling `conn.bind()` before `conn.start_tls()`works OK , but the connection is in clear text while binding :(

Am I doing something wrong?

Thanks in advance

Regards

**Comment by tobiasbaehr** [comment]
Try it with ldaps://54.36.252.50:10389
