### ISSUE TITLE
Filters are not decoded correctly

### ISSUE THREAD

**Issue by voron3x** [cannatag/ldap3#655]
I am using Python 3.6 and pyasn1 version 0.4.2 for receiving and decoding LDAP messages. The issue is that the client application generates filters, which cannot be decoded by pyasn1.

I decode LDAP messages in this way:
```
...
from ldap3.protocol.rfc4511 import LDAPMessage
from ldap3.strategy.sync import SyncStrategy
from pyasn1.codec.ber.decoder import decode
...
raw_messages = SyncStrategy(ldap_connection=conn).receiving()
ldap_resp, _ = decode(raw_message, asn1Spec=LDAPMessage())
...
```

Raw LDAP message:
```
b'0\x82\x01I\x02\x01\x05c\x81\xff\x04\x0fdc=arl,dc=local\n\x01\x02\n\x01\x03\x02\x01\x00\x02\x01\x00\x01\x01\x00\xa0W\xa3\x13\x04\x0bobjectClass\x04\x04user\xa1@\xa3\x1b\x04\rpostOfficeBox\x04\n01107ECBA2\xa3!\x04\x13extensionAttribute1\x04\n01107ECBA20\x81\x83\x04\rpostOfficeBox\x04\tgivenName\x04\x02sn\x04\x04mail\x04\rhomeDirectory\x04\x08memberOf\x04\nobjectGUID\x04\rpostOfficeBox\x04\x13extensionAttribute1\x04\x04mail\x04\x0esAMAccountName\xa0B0%\x04\x161.2.840.113556.1.4.319\x01\x01\xff\x04\x080\x06\x02\x02\x03\xe7\x04\x000\x19\x04\x172.16.840.1.113730.3.4.2'
```

Decoded LDAP message:
```
 messageID=5
 protocolOp=ProtocolOp:
  searchRequest=SearchRequest:
   baseObject=dc=arl,dc=local
   scope=wholeSubtree
   derefAliases=derefAlways
   sizeLimit=0
   timeLimit=0
   typesOnly=False
   filter=Filter:
    and=And:
     objectClass     postOfficeBox

   attributes=AttributeSelection:
    postOfficeBox    givenName    sn    mail    homeDirectory    memberOf    objectGUID    postOfficeBox    extensionAttribute1    mail    sAMAccountName
```

Message captured and decoded by Wireshark. See the complex filter and compare to the output from decoding in Python:
```
Lightweight Directory Access Protocol
    LDAPMessage searchRequest(5) "dc=server,dc=local" wholeSubtree
        messageID: 5
        protocolOp: searchRequest (3)
            searchRequest
                baseObject: dc=server,dc=local
                scope: wholeSubtree (2)
                derefAliases: derefAlways (3)
                sizeLimit: 0
                timeLimit: 0
                typesOnly: False
                Filter: (&(objectClass=user)(|(postOfficeBox=1234567890)(extensionAttribute1=1234567890)))
                    filter: and (0)
                        and: (&(objectClass=user)(|(postOfficeBox=1234567890)(extensionAttribute1=1234567890)))
                            and: 2 items
                                Filter: (objectClass=user)
                                    and item: equalityMatch (3)
                                        equalityMatch
                                            attributeDesc: objectClass
                                            assertionValue: user
                                Filter: (|(postOfficeBox=1234567890)(extensionAttribute1=1234567890))
                                    and item: or (1)
                                        or: (|(postOfficeBox=1234567890)(extensionAttribute1=1234567890))
                                            or: 2 items
                                                Filter: (postOfficeBox=1234567890)
                                                    or item: equalityMatch (3)
                                                        equalityMatch
                                                            attributeDesc: postOfficeBox
                                                            assertionValue: 1234567890
                                                Filter: (extensionAttribute1=1234567890)
                                                    or item: equalityMatch (3)
                                                        equalityMatch
                                                            attributeDesc: extensionAttribute1
                                                            assertionValue: 1234567890
                attributes: 11 items
        [Response In: 30]
        controls: 2 items
			Control
				controlType: 1.2.840.113556.1.4.319 (pagedResultsControl)
				criticality: True
				SearchControlValue
					size: 999
					cookie: <MISSING>
			Control
				controlType: 2.16.840.1.113730.3.4.2 (Manage DSA IT LDAPv3 control)
```

Could you please suggest if my code is wrong or it is a bug in decoding?

Thank you.

**Comment by cannatag** [comment]
Hi, you mean that are not using the ldap3 library to connect to an ldap server, but only to decode messages via pyasn1? In ldap3 there are two decoders, an internal decoder and the pyasn1 decoder. The internal one is faster then the pyasn1 but they should return the same value. You can set the decoder used by the Connection with the internal_decoder=True or False while defining the connection. Can you try with both to see if you get different messages?

**Comment by voron3x** [comment]
Hi, yes i'm using it for very simple auth ldap server (only for bind and search requests and responses) over my DB.

Ok. i'll check internal decoder.

**Comment by voron3x** [comment]
Hm... looks like `decode_message_fast()` can't decode bind_request (BER Type Class - 1, BER Type Tag Number - 0).

```python
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/selector_events.py", line 824, in _read_ready__data_received
    self._protocol.data_received(data)
  File "/home/voron3x/Projects/timandteam/dodone/piggy-bank/ldap_server/management/commands/run_ldap_server.py", line 39, in data_received
    fast_data = decode_message_fast(data)
  File "/home/voron3x/.virtualenvs/piggy-bank/lib/python3.7/site-packages/ldap3/utils/asn1.py", line 104, in decode_message_fast
    decoded = decode_sequence(message, ber_value_offset, ber_len + ber_value_offset, LDAP_MESSAGE_CONTEXT)
  File "/home/voron3x/.virtualenvs/piggy-bank/lib/python3.7/site-packages/ldap3/utils/asn1.py", line 120, in decode_sequence
    ber_decoder = DECODERS[(ber_class, octet & 0b00011111)] if ber_class < 2 else None
KeyError: (1, 0)
```

**Comment by cannatag** [comment]
Try to set “internal_decoder=False” in the Connection object. It uses the pyasn1 standard decoder.

**Comment by voron3x** [comment]
As I understand pyasn1 standard ber decoder with rfc4511.py work fine! I have problem with Filter.And. With simple Filter.EqualityMatch everything work fine. Maybe, 
it's because filter data need some unescape (https://tools.ietf.org/html/rfc4515).

In my case filter is:

```(&(objectClass=user)(|(postOfficeBox=1234567890)(extensionAttribute1=1234567890)))``` 

but BER decoder can produce only

```
   filter=Filter:
    and=And:
     objectClass     postOfficeBox
```

**Comment by cannatag** [comment]
Hi, I can't replicate this.
If I try the ``(&(objectClass=user)(|(postOfficeBox=1234567890)(extensionAttribute1=1234567890)))`` filter I get the following using the internal decoder:
```
>>LDAPMessage:
>> messageID=4
>> protocolOp=ProtocolOp:
>>  searchRequest=SearchRequest:
>>   baseObject=o=test
>>   scope=wholeSubtree
>>   derefAliases=derefAlways
>>   sizeLimit=0
>>   timeLimit=0
>>   typesOnly=False
>>   filter=Filter:
>>    and=And:
>>     Filter:
>>      equalityMatch=EqualityMatch:
>>       attributeDesc=objectClass
>>       assertionValue=user
>>     Filter:
>>      or=Or:
>>       Filter:
>>        equalityMatch=EqualityMatch:
>>         attributeDesc=postOfficeBox
>>         assertionValue=1234567890
>>       Filter:
>>        equalityMatch=EqualityMatch:
>>         attributeDesc=extensionAttribute1
>>         assertionValue=1234567890
>>   attributes=AttributeSelection:
>>    1.1
>> controls=Controls:

Il looks right to me. Can you provide a sample of the code that show the bug?

Thanks,
Giovanni

**Comment by voron3x** [comment]
Can you show me your code?

I use something like this. In my case I receiving data from asyncio callback. And for me it don't work ((
```python
from pyasn1.codec.ber import decoder
from ldap3.protocol import rfc4511

data = b'0\x82\x01I\x02\x01\x05c\x81\xff\x04\x0fdc=arl,dc=local\n\x01\x02\n\x01\x03\x02\x01\x00\x02\x01\x00\x01\x01\x00\xa0W\xa3\x13\x04\x0bobjectClass\x04\x04user\xa1@\xa3\x1b\x04\rpostOfficeBox\x04\n01107ECBA2\xa3!\x04\x13extensionAttribute1\x04\n01107ECBA20\x81\x83\x04\rpostOfficeBox\x04\tgivenName\x04\x02sn\x04\x04mail\x04\rhomeDirectory\x04\x08memberOf\x04\nobjectGUID\x04\rpostOfficeBox\x04\x13extensionAttribute1\x04\x04mail\x04\x0esAMAccountName\xa0B0%\x04\x161.2.840.113556.1.4.319\x01\x01\xff\x04\x080\x06\x02\x02\x03\xe7\x04\x000\x19\x04\x172.16.840.1.113730.3.4.2'

decoded_data, _ = decoder.decode(data, asn1Spec=rfc4511.LDAPMessage())
print(decoded_data)
```

**Comment by cannatag** [comment]
Hi, did you solve this issue?
