### ISSUE TITLE
NTLM conn and samba4 AD

### ISSUE THREAD

**Issue by infomatico** [cannatag/ldap3#663]
hello,

I have a samba4 AD server and I try to bind via ntlm. In smb.conf I set ntlm auth = yes and also ntlm auth = mschapv2-and-ntlmv2-only for test, but not works.

code:

```
server = Server(server_name, get_info=ALL)
    conn = Connection(server, user="{}\\{}".format(domain_name, user_name), password=password, authentication=NTLM)
```
error:
```
Traceback (most recent call last):
  File "./get_dados.py", line 61, in <module>
    main()
  File "./get_dados.py", line 57, in main
    ad_connection()
  File "./get_dados.py", line 38, in ad_connection
    if conn.bind():
  File "/usr/local/lib/python2.7/dist-packages/ldap3/core/connection.py", line 569, in bind
    response = self.do_ntlm_bind(controls)
  File "/usr/local/lib/python2.7/dist-packages/ldap3/core/connection.py", line 1291, in do_ntlm_bind
    response = self.post_send_single_response(self.send('bindRequest', request, controls))
  File "/usr/local/lib/python2.7/dist-packages/ldap3/strategy/sync.py", line 121, in post_send_single_response
    responses, result = self.get_response(message_id)
  File "/usr/local/lib/python2.7/dist-packages/ldap3/strategy/base.py", line 339, in get_response
    raise LDAPSessionTerminatedByServerError(self.connection.last_error)
ldap3.core.exceptions.LDAPSessionTerminatedByServerError: session terminated by server
```
- No firewall blocks
- simple bind works

Any ideas?

**Comment by cannatag** [comment]
``ldap3.core.exceptions.LDAPSessionTerminatedByServerError: session terminated by server`` means that the server itself stops the connection abruptly. Probably he doesn't accept the NTML authentication method. You should check the server logs to get more information.

**Comment by jasperges** [comment]
Hi,

Would it be possible to re-open this issue again. Recently the studio I work for started using Samba AD and we ran into this exact same issue. The sysadmin also looked into it, but the only thing he could find in the log was `stream_terminate_connection: Terminating connection - 'LDAP_PROTOCOL_ERROR'`.

Any help will we greatly appreciated.
