### ISSUE TITLE
auto_bind on Connection behaving strange

### ISSUE THREAD

**Issue by jjmurre** [cannatag/ldap3#676]
When I make a connection like this (using latest pypi version 2.6):
```
>>> with ldap3.Connection(srv, user='admin', password='****') as conn:
...   conn.search(search_base='OU=People,DC=example,DC=com', search_filter='(uid=editor)')
...   print(conn.auto_bind)
...
True
NO_TLS
```
This just, works. However, when I call it with an exclicit autobind, It does not work, but generates an error "Invalid DN response":

```
>>> with ldap3.Connection(srv, user='admin', password='****', auto_bind=ldap3.AUTO_BIND_NO_TLS, raise_exceptions=True) as conn:
...   conn.search(search_base='OU=People,DC=example,DC=com', search_filter='(uid=editor)')
...   print(conn.auto_bind)
... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/aap/lib/python3.6/site-packages/ldap3/core/connection.py", line 325, in __init__
    self.do_auto_bind()
  File "/tmp/aap/lib/python3.6/site-packages/ldap3/core/connection.py", line 342, in do_auto_bind
    self.bind(read_server_info=True)
  File "/tmp/aap/lib/python3.6/site-packages/ldap3/core/connection.py", line 548, in bind
    response = self.post_send_single_response(self.send('bindRequest', request, controls))
  File "/tmp/aap/lib/python3.6/site-packages/ldap3/strategy/sync.py", line 121, in post_send_single_response
    responses, result = self.get_response(message_id)
  File "/tmp/aap/lib/python3.6/site-packages/ldap3/strategy/base.py", line 378, in get_response
    raise LDAPOperationResult(result=result['result'], description=result['description'], dn=result['dn'], message=result['message'], response_type=result['type'])
ldap3.core.exceptions.LDAPInvalidDNSyntaxResult: LDAPInvalidDNSyntaxResult - 34 - invalidDNSyntax - None - invalid DN - bindResponse - None

```
The LDAP server is the default OpenLDAP on Ubuntu 18:04.

**Comment by cannatag** [comment]
Hi, are you sure that the user is called “admin”? Have you tried the full dn form?

**Comment by jjmurre** [comment]
That nailed it! When I used a full dn for the user argument on Connection() it works. I'll close this issue.
