### ISSUE TITLE
Problem with 'not' searches

### ISSUE THREAD

**Issue by midnightlynx** [cannatag/ldap3#73]
After setting up connection c:

```python
c.search('dc=testbase', '(testattribute=true)')  # searches fine
c.search('dc=testbase', '(!(testattribute=true))')  # search throws error in pyasn1
"""
Error:
Traceback (most recent call last):
   File <file info>
    c.search('dc=testbase', "(!(testattribute=true))")
  File "/lib/python3.4/site-packages/ldap3/core/connection.py", line 568, in search
    request = search_operation(search_base, search_filter, search_scope, dereference_aliases, attributes, size_limit, time_limit, types_only, self.server.schema if self.server else None)
  File "/lib/python3.4/site-packages/ldap3/operation/search.py", line 365, in search_operation
    request['filter'] = build_filter(search_filter, schema)  # parse the searchFilter string and compile it starting from the root node
  File "/lib/python3.4/site-packages/ldap3/operation/search.py", line 312, in build_filter
    return compile_filter(parse_filter(search_filter, schema).elements[0])
  File "/lib/python3.4/site-packages/ldap3/operation/search.py", line 256, in compile_filter
    compiled_filter['notFilter'] = boolean_filter
  File "/lib/python3.4/site-packages/pyasn1/type/univ.py", line 824, in __setitem__
    self.setComponentByName(idx, value)
  File "/lib/python3.4/site-packages/pyasn1/type/univ.py", line 859, in setComponentByName
    self._componentType.getPositionByName(name),value,verifyConstraints
  File "/lib/python3.4/site-packages/pyasn1/type/univ.py", line 1093, in setComponentByPosition
    self._verifyComponent(idx, value)
  File "/lib/python3.4/site-packages/pyasn1/type/univ.py", line 848, in _verifyComponent
    raise error.PyAsn1Error('Component value is tag-incompatible: %r vs %r' % (value, t))
pyasn1.error.PyAsn1Error: Component value is tag-incompatible: Not(componentType=NamedTypes(NamedType('innerNotFilter', Filter(componentType=NamedTypes(NamedType('and', And(componentType=None)), NamedType('or', Or(componentType=None)), NamedType('notFilter', Not(componentType=NamedTypes(), tagSet=TagSet((), ))), NamedType('equalityMatch', EqualityMatch(componentType=NamedTypes(NamedType('attributeDesc', AttributeDescription()), NamedType('assertionValue', AssertionValue())))), NamedType('substringFilter', SubstringFilter(componentType=NamedTypes(NamedType('type', AttributeDescription()), NamedType('substrings', Substrings())))), NamedType('greaterOrEqual', GreaterOrEqual(componentType=NamedTypes(NamedType('attributeDesc', AttributeDescription()), NamedType('assertionValue', AssertionValue())))), NamedType('lessOrEqual', LessOrEqual(componentType=NamedTypes(NamedType('attributeDesc', AttributeDescription()), NamedType('assertionValue', AssertionValue())))), NamedType('present', Present()), NamedType('approxMatch', ApproxMatch(componentType=NamedTypes(NamedType('attributeDesc', AttributeDescription()), NamedType('assertionValue', AssertionValue())))), NamedType('extensibleMatch', ExtensibleMatch(componentType=NamedTypes(OptionalNamedType('matchingRule', MatchingRule()), OptionalNamedType('type', Type()), NamedType('matchValue', MatchValue()), DefaultedNamedType('dnAttributes', DnAttributes('False')))))))))).setComponents(Filter(componentType=NamedTypes(NamedType('and', And(componentType=None)), NamedType('or', Or(componentType=None)), NamedType('notFilter', Not(componentType=NamedTypes(), tagSet=TagSet((), ))), NamedType('equalityMatch', EqualityMatch(componentType=NamedTypes(NamedType('attributeDesc', AttributeDescription()), NamedType('assertionValue', AssertionValue())))), NamedType('substringFilter', SubstringFilter(componentType=NamedTypes(NamedType('type', AttributeDescription()), NamedType('substrings', Substrings())))), NamedType('greaterOrEqual', GreaterOrEqual(componentType=NamedTypes(NamedType('attributeDesc', AttributeDescription()), NamedType('assertionValue', AssertionValue())))), NamedType('lessOrEqual', LessOrEqual(componentType=NamedTypes(NamedType('attributeDesc', AttributeDescription()), NamedType('assertionValue', AssertionValue())))), NamedType('present', Present()), NamedType('approxMatch', ApproxMatch(componentType=NamedTypes(NamedType('attributeDesc', AttributeDescription()), NamedType('assertionValue', AssertionValue())))), NamedType('extensibleMatch', ExtensibleMatch(componentType=NamedTypes(OptionalNamedType('matchingRule', MatchingRule()), OptionalNamedType('type', Type()), NamedType('matchValue', MatchValue()), DefaultedNamedType('dnAttributes', DnAttributes('False'))))))).setComponents(None, None, None, EqualityMatch(componentType=NamedTypes(NamedType('attributeDesc', AttributeDescription()), NamedType('assertionValue', AssertionValue()))).setComponents(AttributeDescription(b'testattribute'), AssertionValue(b'true')))) vs Not(componentType=NamedTypes(), tagSet=TagSet((), ))
"""
```

**Comment by midnightlynx** [comment]
Python 3.4.0
ldap3 0.9.8.5
pyasn1 0.1.8

**Comment by cannatag** [comment]
Could you try to backrev pyasn to 0.1.7? It has been recently updated and I have some issues with it I'm working on.

Thanks,
Giovanni

**Comment by cannatag** [comment]
I've released 0.9.8.5.post1 that requires pyasn1 0.1.7. I hope to add compatibility with 0.1.8 in the next release of ldap3.

Bye,
Giovanni

----- Messaggio originale -----
Da: "midnightlynx" <notifications@github.com>
Inviato: ‎24/‎06/‎2015 01:50
A: "cannatag/ldap3" <ldap3@noreply.github.com>
Oggetto: Re: [ldap3] Problem with 'not' searches (#73)

Python 3.4.0
ldap3 0.9.8.5
pyasn1 0.1.8

**Comment by midnightlynx** [comment]
That worked. Thank you for the quick response!

**Comment by cannatag** [comment]
Pls check 0.9.8.5.post2. It should work with pyasn1 0.1.8 too.

**Comment by midnightlynx** [comment]
Works. Thank you.
