### ISSUE TITLE
UnicodeDecodeError when writing binary attribute in entry creation

### ISSUE THREAD

**Issue by fab0l1n** [cannatag/ldap3#766]
Hi,

I encountered an issue writing binary data at entry creation. However, I could skip the attribute and use a modify operation to set the attribute value afterwards with no problem.
Is this intended behavior?

```
Traceback (most recent call last):
  File "C:\Program Files\Python\Python36\lib\site-packages\pyasn1-0.4.2-py3.6.egg\pyasn1\type\univ.py", line 882, in __str__
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x82 in position 1: invalid start byte

During handling of the above exception, another exception occurred:

[...]
    return self.stream.add(dn, object_class, attributes, self.controls)
  File "C:\Program Files\Python\Python36\lib\site-packages\ldap3-2.4.1-py3.6.egg\ldap3\core\connection.py", line 922, in add
  File "C:\Program Files\Python\Python36\lib\site-packages\ldap3-2.4.1-py3.6.egg\ldap3\strategy\base.py", line 303, in send
  File "C:\Program Files\Python\Python36\lib\site-packages\ldap3-2.4.1-py3.6.egg\ldap3\strategy\base.py", line 623, in decode_request
  File "C:\Program Files\Python\Python36\lib\site-packages\ldap3-2.4.1-py3.6.egg\ldap3\operation\add.py", line 64, in add_request_to_dict
  File "C:\Program Files\Python\Python36\lib\site-packages\ldap3-2.4.1-py3.6.egg\ldap3\protocol\convert.py", line 41, in attributes_to_dict
  File "C:\Program Files\Python\Python36\lib\site-packages\ldap3-2.4.1-py3.6.egg\ldap3\protocol\convert.py", line 35, in attribute_to_dict
  File "C:\Program Files\Python\Python36\lib\site-packages\ldap3-2.4.1-py3.6.egg\ldap3\protocol\convert.py", line 35, in <listcomp>
  File "C:\Program Files\Python\Python36\lib\site-packages\pyasn1-0.4.2-py3.6.egg\pyasn1\type\univ.py", line 886, in __str__
pyasn1.error.PyAsn1Error: Can't decode string 'b'0\x82\x06[...]'' with 'utf-8' codec at 'AttributeValue'

```

**Comment by cannatag** [comment]
Hi, this should not happen! Can you provide some code to replicate the issue?

Thanks,
Giovanni

**Comment by fab0l1n** [comment]
I'm really sorry, I wasn't using my venv and therefore working with an ancient version 2.4.1 of ldap3. This is no issue with the current build.
