### ISSUE TITLE
ldap3.core.exceptions.LDAPCursorError: attribute '__getstate__' not found

### ISSUE THREAD

**Issue by superdicdi** [cannatag/ldap3#776]
Traceback (most recent call last):
  File "/usr/local/envs/weibu_ops/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/envs/weibu_ops/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/envs/weibu_ops/lib/python3.6/site-packages/flask/app.py", line 1969, in finalize_request
    response = self.process_response(response)
  File "/usr/local/envs/weibu_ops/lib/python3.6/site-packages/flask/app.py", line 2268, in process_response
    self.session_interface.save_session(self, ctx.session, response)
  File "/usr/local/envs/weibu_ops/lib/python3.6/site-packages/flask_session/sessions.py", line 164, in save_session
    val = self.serializer.dumps(dict(session))
  File "/usr/local/envs/weibu_ops/lib/python3.6/site-packages/ldap3/abstract/entry.py", line 196, in __getattr__
    raise LDAPCursorError(error_message)
ldap3.core.exceptions.LDAPCursorError: attribute '__getstate__' not found
[2020-01-09 21:16:44,686] ERROR in app: Request finalizing failed with an error while handling an error
Traceback (most recent call last):
  File "/usr/local/envs/weibu_ops/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/envs/weibu_ops/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/envs/weibu_ops/lib/python3.6/site-packages/flask/app.py", line 1969, in finalize_request
    response = self.process_response(response)
  File "/usr/local/envs/weibu_ops/lib/python3.6/site-packages/flask/app.py", line 2268, in process_response
    self.session_interface.save_session(self, ctx.session, response)
  File "/usr/local/envs/weibu_ops/lib/python3.6/site-packages/flask_session/sessions.py", line 164, in save_session
    val = self.serializer.dumps(dict(session))
  File "/usr/local/envs/weibu_ops/lib/python3.6/site-packages/ldap3/abstract/entry.py", line 196, in __getattr__
    raise LDAPCursorError(error_message)
ldap3.core.exceptions.LDAPCursorError: attribute '__getstate__' not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/envs/weibu_ops/lib/python3.6/site-packages/flask/app.py", line 1969, in finalize_request
    response = self.process_response(response)
  File "/usr/local/envs/weibu_ops/lib/python3.6/site-packages/flask/app.py", line 2268, in process_response
    self.session_interface.save_session(self, ctx.session, response)
  File "/usr/local/envs/weibu_ops/lib/python3.6/site-packages/flask_session/sessions.py", line 164, in save_session
    val = self.serializer.dumps(dict(session))
  File "/usr/local/envs/weibu_ops/lib/python3.6/site-packages/ldap3/abstract/entry.py", line 196, in __getattr__
    raise LDAPCursorError(error_message)
ldap3.core.exceptions.LDAPCursorError: attribute '__getstate__' not found

**Comment by superdicdi** [comment]
This is my problem！I get an object instead of a value

**Comment by cannatag** [comment]
Hi, can you show the code that is raising the exception? I see you’re using flask to serialize a session. Probably you have to convert the entry object to string values.

**Comment by cfelder** [comment]
May this issue is already addressed in cannatag/ldap3#748 which is included in dev.

Best
Christian

**Comment by superdicdi** [comment]
Yes！You are right. I get an Attribute object instead of a value. and An serialize a session exception was caused. Finally, thank you again！

**Comment by cannatag** [comment]
Fixed in ldap3 v2.7.
