### ISSUE TITLE
Auto_bind failing when password is expired or invalid with no message

### ISSUE THREAD

**Issue by WilliamMiteff** [cannatag/ldap3#796]
I have found that if a bad or expired password is provided for authentication to AD and auto_bind is being used on the connection a LDAPBindError is thrown with no message attached.  The attached file is a simple script that shows this issue.

[example.txt](https://github.com/cannatag/ldap3/files/4281654/example.txt)

Traceback (most recent call last):
  File "test.py", line 8, in <module>
    with authenticate('[server]', '[user]', '[pwd]') as ldapconn:
  File "test.py", line 5, in authenticate
    return Connection(server, username, password,auto_bind=True)
  File "/usr/local/lib/python3.7/site-packages/ldap3/core/connection.py", line 355, in __init__
    self.do_auto_bind()
  File "/usr/local/lib/python3.7/site-packages/ldap3/core/connection.py", line 384, in do_auto_bind
    raise LDAPBindError(self.last_error)
ldap3.core.exceptions.LDAPBindError: None

**Comment by cfelder** [comment]
This is a regression in 2.7. I’ve written a fix in PR #835

**Comment by cannatag** [comment]
fixed in the next release of ldap3
