### ISSUE TITLE
ImportError: cannot import name PyAsn1UnicodeDecodeError

### ISSUE THREAD

**Issue by qq719862911** [cannatag/ldap3#800]
What should I do
In Ubuntu 16.04, python2.7.5, install from the source, and then execute 
"
#coding=utf-8
from ldap3 import Server, Connection, NTLM
def test():
    server1 = Server("***.**.com", port=636, use_ssl=True, get_info='ALL', connect_timeout=5)
    conn = Connection(
        server = server1,
        auto_bind = True,
        authentication = NTLM,
        read_only = False,
        user = 'test\\****',
        password = "!*****",
        fast_decoder=True,
        check_names=True,)
    return conn.user
if __name__ == '__main__':
    print(test())

"
 in python2.5.7 to report an error: 
Traceback (most recent call last):
  File "simpleforldap3.py", line 2, in <module>
    from ldap3 import Server, Connection, NTLM
  File "build/bdist.linux-x86_64/egg/ldap3/__init__.py", line 139, in <module>
  File "build/bdist.linux-x86_64/egg/ldap3/core/connection.py", line 44, in <module>
  File "build/bdist.linux-x86_64/egg/ldap3/operation/compare.py", line 28, in <module>
  File "build/bdist.linux-x86_64/egg/ldap3/operation/search.py", line 41, in <module>
ImportError: cannot import name PyAsn1UnicodeDecodeError

**Comment by dirickxmaarten** [comment]
+1 

CentOS 8.1
pip install ldap3 works fine
after that I get:
```
[root@myhost scripts]# python3
Python 3.6.8 (default, Nov 21 2019, 19:31:34) 
[GCC 8.3.1 20190507 (Red Hat 8.3.1-4)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ldap3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/ldap3/__init__.py", line 139, in <module>
    from .core.connection import Connection
  File "/usr/local/lib/python3.6/site-packages/ldap3/core/connection.py", line 44, in <module>
    from ..operation.compare import compare_operation, compare_request_to_dict
  File "/usr/local/lib/python3.6/site-packages/ldap3/operation/compare.py", line 28, in <module>
    from ..operation.search import ava_to_dict
  File "/usr/local/lib/python3.6/site-packages/ldap3/operation/search.py", line 41, in <module>
    from pyasn1.error import PyAsn1UnicodeDecodeError
ImportError: cannot import name 'PyAsn1UnicodeDecodeError'
>>> 
```

**Comment by jannh** [comment]
This is a problem with the requirements file - It lists a dependency to pyasn1>=0.1.8
However, the import of PyAsn1UnicodeDecodeError only appeared in pyasn1 0.4.6, so if you have an earlier version installed, you run in the given error. The requirements.txt file should therefore be updated.
As a "quickfix", you can do "pip install pyasn1 -U", which will install the latest version of pyasn1 for you.

**Comment by qq719862911** [comment]
It's ready to run thank you

**Comment by jannh** [comment]
Seems like the corresponding PR #802 is still open - do you think it would be a good idea to get it merged before closing the issue?
