### ISSUE TITLE
Error with paged_search_generator (ldap3==2.2.4, pyasn1==0.4.8)

### ISSUE THREAD

**Issue by boxysean** [cannatag/ldap3#823]
### System

- Python version: 3.6.9.
- Pip freeze:
```
ldap3==2.2.4
pyasn1==0.4.8
```

### Issue

Context: I am upgrading my application's python packages. While doing so, I encountered the following stacktrace.

```
Traceback (most recent call last):
  ...
  <My application's stack trace>
  ...
  File "./virtualenv/lib/python3.6/site-packages/ldap3/extend/standard/PagedSearch.py", line 63, in paged_search_generator
    None if cookie is True else cookie)
  File "./virtualenv/lib/python3.6/site-packages/ldap3/core/connection.py", line 763, in search
    self.server.schema if self.server else None)
  File "./virtualenv/lib/python3.6/site-packages/ldap3/operation/search.py", line 363, in search_operation
    request['filter'] = compile_filter(parse_filter(search_filter, schema, auto_escape, auto_encode).elements[0])  # parse the searchFilter string and compile it starting from the root node
  File "./virtualenv/lib/python3.6/site-packages/ldap3/operation/search.py", line 223, in compile_filter
    boolean_filter[pos] = compile_filter(element)
  File "./virtualenv/lib/python3.6/site-packages/ldap3/operation/search.py", line 235, in compile_filter
    boolean_filter['innerNotFilter'] = compile_filter(filter_node.elements[0])
  File "./virtualenv/lib/python3.6/site-packages/ldap3/operation/search.py", line 260, in compile_filter
    matching_filter['dnAttributes'] = DnAttributes(filter_node.assertion['dnAttributes'])
  File "./virtualenv/lib/python3.6/site-packages/pyasn1/type/univ.py", line 107, in __init__
    base.SimpleAsn1Type.__init__(self, value, **kwargs)
  File "./virtualenv/lib/python3.6/site-packages/pyasn1/type/base.py", line 267, in __init__
    value = self.prettyIn(value)
  File "./virtualenv/lib/python3.6/site-packages/pyasn1/type/univ.py", line 258, in prettyIn
    return int(value)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

### Resolution

I decided to upgrade `ldap3` to `2.7` (the latest version at time of this issue submission) and I no longer receive this stacktrace.

I wonder if `ldap3==2.2.4` is not compatible with `pyasn1==0.4.8`, even though the `install_requires` for this version of `ldap3` is `pyasn1>=0.1.8`?

**Comment by cannatag** [comment]
pyasn1 had various braking changes in the last versions. I suggest you to update ldap3 and pyasn1 to the latest version available.

Bye,
Giovanni
