### ISSUE TITLE
Failure to parse extensible filters

### ISSUE THREAD

**Issue by Entreiu** [cannatag/ldap3#862]
When using an OpenLDAP compliant extensible filter such as: (:dn:caseExactMatch:=somestring), the library fails with the following traceback:

```
Traceback (most recent call last):
  File "./ldap_audit.py", line 272, in <module>
    ERR = main()
  File "./ldap_audit.py", line 120, in main
    conn.search(search_base=opts.basedn, search_filter=search_filter)
  File "/usr/local/lib/python3.6/dist-packages/ldap3/core/connection.py", line 836, in search
    check_names=self.check_names)
  File "/usr/local/lib/python3.6/dist-packages/ldap3/operation/search.py", line 371, in search_operation
    request['filter'] = compile_filter(parse_filter(search_filter, schema, auto_escape, auto_encode, validator, check_names).elements[0])  # parse the searchFilter string and compile it starting from the root node
  File "/usr/local/lib/python3.6/dist-packages/ldap3/operation/search.py", line 205, in parse_filter
    current_node.append(evaluate_match(search_filter[start_pos:end_pos], schema, auto_escape, auto_encode, validator, check_names))
  File "/usr/local/lib/python3.6/dist-packages/ldap3/operation/search.py", line 140, in evaluate_match
    assertion = {'attr': attribute_name, 'value': validate_assertion_value(schema, attribute_name, right_part, auto_escape, auto_encode, validator, check_names), 'matchingRule': matching_rule, 'dnAttributes': dn_attributes}
  File "/usr/local/lib/python3.6/dist-packages/ldap3/protocol/convert.py", line 149, in validate_assertion_value
    value = validate_attribute_value(schema, name, value, auto_encode, validator=validator, check_names=check_names)
  File "/usr/local/lib/python3.6/dist-packages/ldap3/protocol/convert.py", line 159, in validate_attribute_value
    if ';' in name:
TypeError: argument of type 'bool' is not iterable
```

It appears that in operation/search.py the function evaluate_match fails to assign a valid value to the variable attribute_name before passing the value on to the function validate_assertion_value() and eventually validate_attribute_name(), which treats the default value of False as a string, resulting in the error.

This can be demonstrated with the following search:

`connection.search(search_base=basedn, search_filter='(:caseExactMatch:=somestring)')`

Changing the search_filter to `'(:dn:caseExactMatch:=somestring)'` does not alleviate the issue.

Using native LDAP search tools succeeds with either of the above filters.

**Comment by Entreiu** [comment]
I failed to note, I'm using Ubuntu with the following:
```
Python 3.6.9 (default, Jul 17 2020, 12:50:27) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ldap3
>>> ldap3.__version__
'2.8'
```
