### ISSUE TITLE
Automatic Bind on connections fail with LDAPBindError after upgrade to 2.8

### ISSUE THREAD

**Issue by wsidl** [cannatag/ldap3#864]
I could previously create a connection to my AD server and auto_bind with ease. Since upgrading to 2.8 and had the Windows Credential renew, I can no longer login with auto_bind.

Details:
- Windows 7/10
- AD Server (Microsoft Windows Server 2008)

code:
```python
srv = ldap3.Server('ldap_server', get_info=ldap3.ALL, use_ssl=True)
conn = ldap3.Connection(srv, 'cn=User,ou=Services,ou=group,dc=domain,dc=local', '....', auto_bind=True)
```
generates:
```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "\site-packages\ldap3\core\connection.py", line 356, in __init__
    self._do_auto_bind()
  File "\site-packages\ldap3\core\connection.py", line 405, in _do_auto_bind
    raise LDAPBindError(error)
LDAPBindError: automatic bind not successful - invalidCredentials
```
If I downgrade the library to 2.7 (ldap3==2.7), and run this code again, it works as expected. On top of this, once I am able to get the credentials generated locally, if I upgrade again to ldap3==2.8, this code segment will work.

**Comment by JKocerka** [comment]
I have a very similar error:
```
  File "/usr/local/lib/python3.8/site-packages/ldap3/abstract/cursor.py", line 625, in search
    self._execute_query(query_scope, attributes)
  File "/usr/local/lib/python3.8/site-packages/ldap3/abstract/cursor.py", line 341, in _execute_query
    with self.connection:
  File "/usr/local/lib/python3.8/site-packages/ldap3/core/connection.py", line 534, in __enter__
    raise LDAPBindError('unable to bind')
ldap3.core.exceptions.LDAPBindError: unable to bind
```

I'm using mockup connection (server from json definition) and `MOCK_SYNC` strategy. 
The whole code is running on the docker container (`python:slim`).

Works ok with library set to 2.7, after upgrading it throws an error.

**Comment by cannatag** [comment]
Hi, I see you’re using the MOCK_SYNC strategy, could you send me a snippet of code (including the json definition) that raises the error?

Thanks,
Giovanni

**Comment by JKocerka** [comment]
Unfortunately I can't share it as it's a dump from a real AD server and I'm not allowed to share it anywhere. 

I can try next week to get the same behaviour on a config without any sensitive data if you can not reproduce it anyhow else.
