### ISSUE TITLE
rebind with mock sync strategy raise a LDAPBindError

### ISSUE THREAD

**Issue by fsaintma** [cannatag/ldap3#886]
Hi

I use mock sync strategy (i.e ldap3==2.8.1) and my test calls rebind method. I declare a Connection without `raise_exceptions=True` parameter and I expect to get a True or False result.
I provide you the following code which raise a LDAPBindError exception. It seems that after trying once with invalid credentials the second time raise the exception because the connection is not closed properly by context manager. Of course with a connection to a real OpenLdap server the exception is not raised and we have the expected behaviour.

Thanks for your help
```
#! /usr/bin/env python
# -*- coding:utf-8 -*

from ldap3 import Connection, MOCK_SYNC, Server

fake_server = Server('my_fake_server')
fake_conn = Connection(fake_server,
                       'uid=test,dc=test,dc=fr',
                       'test',
                       client_strategy=MOCK_SYNC)
fake_conn.strategy.add_entry('uid=test,dc=test,dc=fr',
                             {'userPassword': 'test'})
fake_conn.strategy.add_entry('uid=test2,dc=test,dc=fr',
                             {'userPassword': 'test'})
fake_conn.strategy.add_entry('uid=test3,dc=test,dc=fr',
                             {'userPassword': 'test'})
with fake_conn as conn:
    print(conn.rebind('uid=test2,dc=test,dc=fr', 'test'))
    print(conn.rebind('uid=test3,dc=test,dc=fr', 'test'))
    print(conn.rebind('uid=test2,dc=test,dc=fr', 'bad'))
    print(conn.rebind('uid=test2,dc=test,dc=fr', 'bad'))
    print(conn.rebind('uid=test3,dc=test,dc=fr', 'bad'))
with fake_conn as conn:
    print(conn.rebind('uid=test2,dc=test,dc=fr', 'test'))
```
The output:
```
python3 test_mock_ldap.py 
True
True
False
False
False
Traceback (most recent call last):
  File "test_mock_ldap.py", line 23, in <module>
    with fake_conn as conn:
  File "/home/fsaintma/.local/lib/python3.6/site-packages/ldap3/core/connection.py", line 534, in __enter__
    raise LDAPBindError('unable to bind')
ldap3.core.exceptions.LDAPBindError: unable to bind

```

**Comment by cannatag** [comment]
Hi, in your code with the last rebind in the first context manager you set the user to the "bad" credentials. When you exit the context manager the connection is closed, but it retains the last rebound user, even if it has a bas password. 
When you open the connection again in the second context manager the last credentials are used again, so you get the LDAPBindError exception. You must recreate the connection object with the right credentials to properly open the connection in the second context_manager:

with fake_conn as conn:
    print(conn.rebind('uid=test2,dc=test,dc=fr', 'test'))
    print(conn.rebind('uid=test3,dc=test,dc=fr', 'test'))
    print(conn.rebind('uid=test2,dc=test,dc=fr', 'bad'))
    print(conn.rebind('uid=test2,dc=test,dc=fr', 'bad'))
    print(conn.rebind('uid=test3,dc=test,dc=fr', 'bad'))

fake_conn.user = 'uid=test,dc=test,dc=fr'
fake_conn.password = 'test'

with fake_conn as conn:
    print(conn.rebind('uid=test2,dc=test,dc=fr', 'test'))
