### ISSUE TITLE
response to ldif failing

### ISSUE THREAD

**Issue by DriftedPrism** [cannatag/ldap3#935]
Need some help. I can't get this response to ldif to work. 

`c = Connection(server, admin, password, client_strategy=SAFE_SYNC, auto_bind=True)`

`result = c.search('ou=users,dc=foo,dc=com', filter,  attributes = ['*'])`

This fails
`ldif_output = c.response_to_ldif(result)`

`Traceback (most recent call last):
  File "/Users/Git/iam/python_scripts/getLdapUserByUid.py", line 66, in <module>
    ldif_output = c.response_to_ldif(result)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ldap3/core/connection.py", line 1447, in response_to_ldif
    ldif_lines = operation_to_ldif('searchResponse', search_result, all_base64, sort_order=sort_order)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ldap3/protocol/rfc2849.py", line 221, in operation_to_ldif
    lines = search_response_to_ldif(entries, all_base64, sort_order)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ldap3/protocol/rfc2849.py", line 129, in search_response_to_ldif
    if not entry or entry['type'] != 'searchResEntry':
TypeError: 'bool' object is not subscriptable`

**Comment by zorn96** [comment]
hi @DriftedPrism ! it looks like you're using the `response_to_ldif` function slightly incorrectly.

the LDAP result is not the LDAP response (result gives you a summary of what happened and the response contains 1 or more entries with actual LDAP information). you're using the former, not the latter

you can either access the responses from the query and use those
`ldif_output = c.response_to_ldif(c.response)`
or just leave the keyword arguments empty, and the connection will automatically use the latest response (see: https://ldap3.readthedocs.io/en/latest/ldif.html)
`ldif_output = c.response_to_ldif()`

let me know if you have any further questions
